# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Parallelstore resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
@base.Hidden
class ParallelstoreBeta(base.Group):
  """Manage Parallelstore resources."""


