// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package nodejs

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/googleapis/librarian/internal/config"
)

func TestClean(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name        string
		keep        []string
		setupFiles  []string
		contentMap  map[string]string
		wantDeleted []string
	}{
		{
			name: "protos are deleted only from protos",
			setupFiles: []string{
				"protos/a.proto",
				"protos/kept.proto",
				"protos/subdir/a.proto",
				"other/a.proto",
			},
			keep: []string{"protos/kept.proto"},
			wantDeleted: []string{
				"protos/a.proto",
				"protos/subdir/a.proto",
			},
		},
		{
			name: "json files are deleted only from src",
			setupFiles: []string{
				"src/x.json",
				"src/subdir/x.json",
				"src/subdir/kept.json",
				"protos/x.json",
				"root.json",
			},
			keep: []string{"src/subdir/kept.json"},
			wantDeleted: []string{
				"src/x.json",
				"src/subdir/x.json",
			},
		},
		{
			name: "js and ts files are only deleted if they have markers",
			setupFiles: []string{
				"src/x.js",
				"src/handwritten.js",
				"src/x.ts",
			},
			contentMap: map[string]string{
				"src/x.js":           "comments\n" + string(autogeneratedMarker) + "\ncode",
				"src/handwritten.js": "code",
				"src/x.ts":           "comments\n" + string(autogeneratedMarker) + "\ncode",
			},
			wantDeleted: []string{
				"src/x.js",
				"src/x.ts",
			},
		},
		{
			name: "simple files obey keep",
			setupFiles: []string{
				"protos/protos.js",
				"protos/protos.json",
				"samples/package.json",
				"other.json",
			},
			keep: []string{"protos/protos.json"},
			wantDeleted: []string{
				"protos/protos.js",
				"samples/package.json",
			}},
	} {
		t.Run(test.name, func(t *testing.T) {
			repoRoot := t.TempDir()
			lib := &config.Library{
				Name:   "test",
				Output: filepath.Join(repoRoot, "packages", "test"),
				Keep:   test.keep,
			}
			for _, file := range test.setupFiles {
				createFileAndDirectories(t, filepath.Join(lib.Output, file), test.contentMap[file])
			}
			if err := Clean(lib); err != nil {
				t.Fatal(err)
			}
			verifyFileDeletions(t, lib.Output, test.setupFiles, test.wantDeleted)
		})
	}
}

func verifyFileDeletions(t *testing.T, dir string, setupFiles, wantDeleted []string) {
	t.Helper()
	for _, file := range setupFiles {
		fullPath := filepath.Join(dir, file)
		_, err := os.Stat(fullPath)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			t.Fatal(err)
		}
		got := err != nil
		want := slices.Contains(wantDeleted, file)
		if got != want {
			t.Errorf("file %s deleted: got %t, want %t", file, got, want)
		}
	}
}

func createFileAndDirectories(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}
