// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/iancoleman/strcase"
)

type groupTracks struct {
	ga    *CommandGroup
	beta  *CommandGroup
	alpha *CommandGroup
}

func writeSurface(outputDir string, baseModule string, surface *Surface) error {
	return writeGroup(outputDir, baseModule, surface.Root, surface.Tracks)
}

func writeGroup(outputDir string, baseModule string, g *CommandGroup, tracks []string) error {
	if g == nil {
		return nil
	}

	moduleName := strcase.ToSnake(g.Name)
	groupDir := filepath.Join(outputDir, moduleName)
	if err := os.MkdirAll(groupDir, 0755); err != nil {
		return err
	}

	if err := writeCommandGroupFile(groupDir, baseModule, g.Name, g, tracks); err != nil {
		return err
	}

	if err := writeGroupCommands(groupDir, g, tracks); err != nil {
		return err
	}

	return writeGroupSubgroups(groupDir, baseModule, g, tracks)
}

func writeGroupCommands(groupDir string, g *CommandGroup, tracks []string) error {
	for verb, cmd := range g.Commands {
		if err := writeCommandFiles(groupDir, verb, cmd, tracks); err != nil {
			return err
		}
	}
	return nil
}

func writeGroupSubgroups(groupDir string, baseModule string, g *CommandGroup, tracks []string) error {
	for _, subGroup := range g.Groups {
		if err := writeGroup(groupDir, baseModule, subGroup, tracks); err != nil {
			return err
		}
	}
	return nil
}

func writeCommandGroupFile(dir string, baseModule string, name string, g *CommandGroup, tracks []string) error {
	initPath := filepath.Join(dir, "__init__.py")
	extPath := filepath.Join(dir, "_init_extensions.py")

	var primaryHelpText string = g.HelpText
	var path []string = g.Path
	var trackViews []trackView
	for _, t := range tracks {
		var suffix string
		switch t {
		case "GA":
			suffix = "Ga"
		case "BETA":
			suffix = "Beta"
		case "ALPHA":
			suffix = "Alpha"
		}
		trackViews = append(trackViews, trackView{Name: t, Suffix: suffix})
	}

	modulePathParts := make([]string, 0, 2+len(path))
	if baseModule != "" {
		modulePathParts = append(modulePathParts, baseModule)
		modulePathParts = append(modulePathParts, "surface")
	}
	for _, p := range path {
		modulePathParts = append(modulePathParts, strcase.ToSnake(p))
	}
	fullModulePath := strings.Join(modulePathParts, ".")

	isRoot := len(path) <= 1

	view := commandGroupView{
		Name:       name,
		ModulePath: fullModulePath,
		HelpText:   primaryHelpText,
		Year:       time.Now().Year(),
		IsRoot:     isRoot,
		Tracks:     trackViews,
	}

	var buf bytes.Buffer
	if err := commandGroupTemplate.Execute(&buf, view); err != nil {
		return err
	}

	if err := os.WriteFile(initPath, []byte(strings.TrimSpace(buf.String())+"\n"), 0644); err != nil {
		return err
	}

	buf.Reset()
	if err := initExtensionsTemplate.Execute(&buf, view); err != nil {
		return err
	}

	return os.WriteFile(extPath, []byte(strings.TrimSpace(buf.String())+"\n"), 0644)
}

type trackView struct {
	Name   string
	Suffix string
}

type commandGroupView struct {
	Name       string
	ModulePath string
	HelpText   string
	Year       int
	IsRoot     bool
	Tracks     []trackView
}

var commandGroupTemplate = template.Must(template.New("__init__.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(autogenTemplate + `"""{{.HelpText}}"""

from googlecloudsdk.calliope import base
from {{.ModulePath}} import _init_extensions as extensions


{{range .Tracks}}@base.ReleaseTracks(base.ReleaseTrack.{{.Name}})
@base.Autogenerated
class {{$.Name | toCamel}}{{.Suffix}}(extensions.{{$.Name | toCamel}}{{.Suffix}}):
  """{{$.HelpText}}"""


{{end}}
`))

var initExtensionsTemplate = template.Must(template.New("_init_extensions.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(licenseTemplate + `"""File to add optional custom code to extend __init__.py."""` + "\n" + `from googlecloudsdk.calliope import base


class {{$.Name | toCamel}}Alpha(base.Group):
  """Optional no-auto-generated code for ALPHA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}

class {{$.Name | toCamel}}Beta(base.Group):
  """Optional no-auto-generated code for BETA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}

class {{$.Name | toCamel}}Ga(base.Group):
  """Optional no-auto-generated code for GA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}`))
