# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Defines the configuration version.
# The only possible value is "2".
version: "2"
linters:
  # See https://golangci-lint.run/usage/linters for details.
  default: none
  enable:
    - containedctx
    - contextcheck
    - fatcontext
    - godoclint
    - godot
    - goheader
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
    - unused
    - usetesting
  settings:
    godoclint:
      default: all
      options:
        max-len:
          length: 120
    goheader:
      template: |-
        Copyright {{ YEAR }} Google LLC

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            https://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
      values:
        regexp:
          YEAR: "202[0-9]"
  exclusions:
    rules:
      - path: internal/legacylibrarian/
        linters:
          - godoclint
          - revive
      - path: _test\.go$
        linters:
          - godoclint
      - linters: [revive, staticcheck]
        text: "redefines-builtin-id|package-comments|unused-parameter|empty-block|QF10[0-9]+|SA1024|grpc.Dial|grpc.WithInsecure|grpc.WithBlock|CredentialsFromJSON|internal/pretty|var-declaration|unnecessary-else|trace\\.go|rpcreplay"
      - linters: [revive]
        text: "receiver name [a-zA-Z]+[0-9]* should be consistent with previous receiver name"
      - linters: [revive]
        text: "exported const AllUsers|AllAuthenticatedUsers|RoleOwner|SSD|HDD|PRODUCTION|DEVELOPMENT should have comment"
      - linters: [revive]
        text: "exported func Value returns unexported type pretty.val"
      - linters: [revive]
        text: "exported func (Increment|FieldTransformIncrement|FieldTransformMinimum|FieldTransformMaximum) returns unexported type firestore.transform"
      - linters: [revive]
        text: "var-naming|increment-decrement|exported: type name will be used as|don't use an underscore in package name|avoid meaningless package names|don't use underscores in Go names|comment on exported type|should have comment or be unexported|exported: exported const"
      - path: "gen\\.go"
        linters: [revive]
      - path: "apiv[0-9]+"
        linters: [revive]
