# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Iam policyBinding resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class PolicyBindingsGa(base.Group):
  """Manage Iam policyBinding resources."""


