# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Developerconnect user resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class UsersGa(base.Group):
  """Manage Developerconnect user resources."""


