# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Developerconnect connection resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ConnectionsGa(base.Group):
  """Manage Developerconnect connection resources."""


