// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
	"github.com/googleapis/librarian/internal/sidekick/parser"
	"github.com/googleapis/librarian/internal/sources"
)

func TestGenerate_GRPCServiceFiles(t *testing.T) {
	for _, test := range []struct {
		name          string
		serviceName   string
		productPath   string
		year          string
		sourceFile    string
		wantFileCount int
		wantContent   string
	}{
		{
			name:          "request id service with custom year and source file",
			serviceName:   "RequestIdService",
			productPath:   "generator/integration_tests/golden/v1",
			year:          "2024",
			sourceFile:    "generator/integration_tests/test_request_id.proto",
			wantFileCount: 28,
			wantContent: `// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: generator/integration_tests/test_request_id.proto
`,
		},
		{
			name:          "deprecated service with default year",
			serviceName:   "DeprecatedService",
			productPath:   "custom/product/path",
			year:          "2026",
			sourceFile:    "generator/integration_tests/test_deprecated.proto",
			wantFileCount: 28,
			wantContent: `// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: generator/integration_tests/test_deprecated.proto
`,
		},
		{
			name:          "service without product path",
			serviceName:   "GoldenKitchenSink",
			productPath:   "",
			year:          "2022",
			sourceFile:    "generator/integration_tests/test.proto",
			wantFileCount: 28,
			wantContent: `// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: generator/integration_tests/test.proto
`,
		},
		{
			name:          "service without source file",
			serviceName:   "EchoService",
			productPath:   "v1",
			year:          "2026",
			sourceFile:    "",
			wantFileCount: 28,
			wantContent: `// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
`,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outdir := t.TempDir()
			svc := api.NewTestService(test.serviceName)
			model := api.NewTestAPI(nil, nil, []*api.Service{svc})
			if test.sourceFile != "" {
				model.DefinitionLocations = map[string]api.SourceLocation{
					svc.ID: {Filename: test.sourceFile, Line: 10},
				}
			}

			libCfg := &config.CppLibrary{
				ProductPath:          test.productPath,
				InitialCopyrightYear: test.year,
			}

			if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
				t.Fatal(err)
			}

			expectedFiles := ServiceGeneratedFiles(test.productPath, test.serviceName)
			if len(expectedFiles) != test.wantFileCount {
				t.Fatalf("unexpected expected file count: want %d, got %d", test.wantFileCount, len(expectedFiles))
			}

			for _, gen := range expectedFiles {
				fullPath := filepath.Join(outdir, gen.OutputPath)
				content, err := os.ReadFile(fullPath)
				if err != nil {
					t.Fatalf("expected file not generated %q: %v", gen.OutputPath, err)
				}
				s := string(content)
				if !strings.HasPrefix(s, test.wantContent) {
					t.Logf("file: %s", gen.OutputPath)
					t.Errorf("missing expected prologue prefix:\nwant prefix:\n%s\ngot:\n%s", test.wantContent, s)
				}
				if strings.HasSuffix(gen.OutputPath, ".h") {
					guard := FormatHeaderIncludeGuard(gen.OutputPath)
					extractBlock(t, s, "#ifndef "+guard, "\n\n")
					extractBlock(t, s, "#endif  // "+guard, "\n")
				} else if strings.HasSuffix(gen.OutputPath, ".cc") {
					if !strings.Contains(s, "#include ") {
						t.Errorf("file %s: missing #include directives", gen.OutputPath)
					}
				}

				if !strings.HasSuffix(gen.OutputPath, "sources.cc") {
					extractBlock(t, s, "namespace google {", "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN\n")
					extractBlock(t, s, "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END\n", "}  // namespace google\n")
				}
			}
		})
	}
}

func TestGenerate_GRPCServiceFiles_HeadersAndIncludes(t *testing.T) {
	requireProtoc(t)

	srcs := &sources.Sources{
		Googleapis:  filepath.Join("..", "..", "testdata", "googleapis"),
		ProtobufSrc: filepath.Join("testdata", "protos"),
	}
	sourceConfig := &sources.SourceConfig{
		Sources:     srcs,
		ActiveRoots: []string{"protobuf-src", "googleapis"},
		IncludeList: []string{"test_request_id.proto"},
	}
	modelConfig := &parser.ModelConfig{
		Language:            config.LanguageCpp,
		SpecificationFormat: config.SpecProtobuf,
		SpecificationSource: "generator/integration_tests",
		ServiceConfig:       "generator/integration_tests/test_request_id.yaml",
		Source:              sourceConfig,
	}

	model, err := parser.CreateModel(modelConfig)
	if err != nil {
		t.Fatal(err)
	}
	if err := api.Validate(model); err != nil {
		t.Fatal(err)
	}

	outdir := t.TempDir()
	libCfg := &config.CppLibrary{
		ProductPath:                   "generator/integration_tests/golden/v1",
		InitialCopyrightYear:          "2024",
		RetryableStatusCodes:          []string{"kUnavailable"},
		GenAsyncRPCs:                  []string{"CreateFoo"},
		OverrideServiceConfigYAMLName: "generator/integration_tests/test_request_id.yaml",
	}

	if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
		t.Fatal(err)
	}

	expectedFiles := ServiceGeneratedFiles(libCfg.ProductPath, "RequestIdService")
	if len(expectedFiles) != 28 {
		t.Fatalf("expected 28 files, got %d", len(expectedFiles))
	}

	goldenDir := filepath.Join("testdata", "golden", "v1")
	prefix := libCfg.ProductPath + "/"

	wantContent := `// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: generator/integration_tests/test_request_id.proto
`

	for _, gen := range expectedFiles {
		t.Run(gen.OutputPath, func(t *testing.T) {
			fullPath := filepath.Join(outdir, gen.OutputPath)
			content, err := os.ReadFile(fullPath)
			if err != nil {
				t.Fatalf("missing expected generated file %q: %v", gen.OutputPath, err)
			}
			got := string(content)

			if !strings.HasPrefix(got, wantContent) {
				t.Errorf("file %s: prologue mismatch", gen.OutputPath)
			}

			relPath := strings.TrimPrefix(gen.OutputPath, prefix)
			goldenPath := filepath.Join(goldenDir, relPath)
			goldenContentBytes, err := os.ReadFile(goldenPath)
			if err != nil {
				t.Fatalf("missing golden file %q: %v", goldenPath, err)
			}
			golden := string(goldenContentBytes)

			if strings.HasSuffix(gen.OutputPath, ".h") {
				guard := FormatHeaderIncludeGuard(gen.OutputPath)

				// Compare opening guard.
				gotGuard := extractBlock(t, got, "#ifndef "+guard, "\n\n")
				wantGuard := extractBlock(t, golden, "#ifndef "+guard, "\n\n")
				if diff := cmp.Diff(wantGuard, gotGuard); diff != "" {
					t.Logf("file %s opening guard", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}

				// Compare closing guard.
				gotClosing := extractBlock(t, got, "#endif  // "+guard, "\n")
				wantClosing := extractBlock(t, golden, "#endif  // "+guard, "\n")
				if diff := cmp.Diff(wantClosing, gotClosing); diff != "" {
					t.Logf("file %s closing guard", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}

				// Compare includes block.
				gotIncludes := extractBlock(t, got, "#include ", "\n\n")
				wantIncludes := extractBlock(t, golden, "#include ", "\n\n")
				if diff := cmp.Diff(wantIncludes, gotIncludes); diff != "" {
					t.Logf("file %s includes", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}
			} else if strings.HasSuffix(gen.OutputPath, "sources.cc") {
				gotBlock := extractBlock(t, got, "// NOLINTBEGIN", "// NOLINTEND(bugprone-suspicious-include)\n")
				wantBlock := extractBlock(t, golden, "// NOLINTBEGIN", "// NOLINTEND(bugprone-suspicious-include)\n")
				if diff := cmp.Diff(wantBlock, gotBlock); diff != "" {
					t.Logf("file %s sources block", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}
			} else if strings.HasSuffix(gen.OutputPath, ".cc") {
				gotIncludes := extractBlock(t, got, "#include ", "\n\n")
				wantIncludes := extractBlock(t, golden, "#include ", "\n\n")
				if diff := cmp.Diff(wantIncludes, gotIncludes); diff != "" {
					t.Logf("file %s includes", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}
			}

			if !strings.HasSuffix(gen.OutputPath, "sources.cc") {
				gotNsOpen := extractBlock(t, got, "namespace google {", "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN\n")
				wantNsOpen := extractBlock(t, golden, "namespace google {", "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN\n")
				if diff := cmp.Diff(wantNsOpen, gotNsOpen); diff != "" {
					t.Logf("file %s namespace open", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}

				gotNsClose := extractBlock(t, got, "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END\n", "}  // namespace google\n")
				wantNsClose := extractBlock(t, golden, "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END\n", "}  // namespace google\n")
				if diff := cmp.Diff(wantNsClose, gotNsClose); diff != "" {
					t.Logf("file %s namespace close", gen.OutputPath)
					t.Errorf("mismatch (-want +got):\n%s", diff)
				}
			}
		})
	}
}

func TestGenerate_GRPCServiceFiles_ClassSkeletons(t *testing.T) {
	requireProtoc(t)

	for _, tc := range []struct {
		name          string
		serviceName   string
		includeList   []string
		serviceConfig string
		year          string
		retryCodes    []string
		asyncRPCs     []string
		ns            string
		internalNs    string
		mocksNs       string
		hasLRO        bool
		hasStreaming  bool
		hasRequestId  bool
		isDeprecated  bool
	}{
		{
			name:          "request_id_service",
			serviceName:   "RequestIdService",
			includeList:   []string{"test_request_id.proto"},
			serviceConfig: "generator/integration_tests/test_request_id.yaml",
			year:          "2024",
			retryCodes:    []string{"kUnavailable"},
			asyncRPCs:     []string{"CreateFoo"},
			ns:            "golden_v1",
			internalNs:    "golden_v1_internal",
			mocksNs:       "golden_v1_mocks",
			hasLRO:        true,
			hasStreaming:  false,
			hasRequestId:  true,
			isDeprecated:  false,
		},
		{
			name:          "golden_thing_admin",
			serviceName:   "GoldenThingAdmin",
			includeList:   []string{"test.proto", "backup.proto"},
			serviceConfig: "generator/integration_tests/test.yaml",
			year:          "2022",
			retryCodes:    []string{"kDeadlineExceeded", "kUnavailable"},
			ns:            "golden_v1",
			internalNs:    "golden_v1_internal",
			mocksNs:       "golden_v1_mocks",
			hasLRO:        true,
			hasStreaming:  false,
			hasRequestId:  false,
			isDeprecated:  false,
		},
		{
			name:          "golden_kitchen_sink",
			serviceName:   "GoldenKitchenSink",
			includeList:   []string{"test.proto", "backup.proto"},
			serviceConfig: "generator/integration_tests/test.yaml",
			year:          "2022",
			retryCodes:    []string{"kInternal", "kUnavailable"},
			ns:            "golden_v1",
			internalNs:    "golden_v1_internal",
			mocksNs:       "golden_v1_mocks",
			hasLRO:        false,
			hasStreaming:  true,
			hasRequestId:  false,
			isDeprecated:  false,
		},
		{
			name:          "deprecated_service",
			serviceName:   "DeprecatedService",
			includeList:   []string{"test_deprecated.proto"},
			serviceConfig: "",
			year:          "2024",
			retryCodes:    []string{"kUnavailable"},
			ns:            "golden_v1",
			internalNs:    "golden_v1_internal",
			mocksNs:       "golden_v1_mocks",
			hasLRO:        false,
			hasStreaming:  false,
			hasRequestId:  false,
			isDeprecated:  true,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			srcs := &sources.Sources{
				Googleapis:  filepath.Join("..", "..", "testdata", "googleapis"),
				ProtobufSrc: filepath.Join("testdata", "protos"),
			}
			sourceConfig := &sources.SourceConfig{
				Sources:     srcs,
				ActiveRoots: []string{"protobuf-src", "googleapis"},
				IncludeList: tc.includeList,
			}
			modelConfig := &parser.ModelConfig{
				Language:            config.LanguageCpp,
				SpecificationFormat: config.SpecProtobuf,
				SpecificationSource: "generator/integration_tests",
				ServiceConfig:       tc.serviceConfig,
				Source:              sourceConfig,
			}

			model, err := parser.CreateModel(modelConfig)
			if err != nil {
				t.Fatal(err)
			}
			if err := api.Validate(model); err != nil {
				t.Fatal(err)
			}

			outdir := t.TempDir()
			libCfg := &config.CppLibrary{
				ProductPath:                   "generator/integration_tests/golden/v1",
				InitialCopyrightYear:          tc.year,
				RetryableStatusCodes:          tc.retryCodes,
				GenAsyncRPCs:                  tc.asyncRPCs,
				OverrideServiceConfigYAMLName: tc.serviceConfig,
			}

			if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
				t.Fatal(err)
			}

			goldenDir := filepath.Join("testdata", "golden", "v1")
			prefix := libCfg.ProductPath + "/"

			readGenAndGolden := func(outputPath string) (string, string) {
				fullPath := filepath.Join(outdir, outputPath)
				content, err := os.ReadFile(fullPath)
				if err != nil {
					t.Fatalf("missing expected generated file %q: %v", outputPath, err)
				}
				relPath := strings.TrimPrefix(outputPath, prefix)
				goldenPath := filepath.Join(goldenDir, relPath)
				goldenContentBytes, err := os.ReadFile(goldenPath)
				if err != nil {
					t.Fatalf("missing golden file %q: %v", goldenPath, err)
				}
				return string(content), string(goldenContentBytes)
			}

			assertBlockMatch := func(fileDesc, got, golden, startStr, endStr string) {
				t.Helper()
				gotBlock := extractBlock(t, got, startStr, endStr)
				wantBlock := extractBlock(t, golden, startStr, endStr)
				if diff := cmp.Diff(wantBlock, gotBlock); diff != "" {
					t.Errorf("%s mismatch (-want +got):\n%s", fileDesc, diff)
				}
			}

			svc := tc.serviceName
			clientClass := ClientClassName(svc)
			connClass := ConnectionClassName(svc)
			connImplClass := ConnectionImplClassName(svc)
			idempotencyClass := ConnectionIdempotencyPolicyClassName(svc)
			mockConnClass := MockConnectionClassName(svc)
			stubClass := StubClassName(svc)
			defaultStubClass := DefaultStubClassName(svc)
			authClass := AuthDecoratorClassName(svc)
			loggingClass := LoggingDecoratorClassName(svc)
			metadataClass := MetadataDecoratorClassName(svc)
			tracingConnClass := TracingConnectionClassName(svc)
			tracingStubClass := TracingStubClassName(svc)
			retryPolicy := RetryPolicyName(svc)
			limitedErrorCount := LimitedErrorCountRetryPolicyName(svc)
			limitedTime := LimitedTimeRetryPolicyName(svc)
			retryTraits := RetryTraitsName(svc)

			// 1. client.h
			{
				got, golden := readGenAndGolden(ClientHeaderPath(libCfg.ProductPath, svc))
				clientDeclStart := "class " + clientClass + " {\n public:\n  explicit " + clientClass + "(std::shared_ptr<" + connClass + "> connection, Options opts = {});\n  ~" + clientClass + "();"
				if tc.isDeprecated {
					clientDeclStart = "class\n GOOGLE_CLOUD_CPP_DEPRECATED(\n      \"" + svc + " has been deprecated and will be turned down in the future.\"\n)\n" + clientClass + " {\n public:\n  explicit " + clientClass + "(std::shared_ptr<" + connClass + "> connection, Options opts = {});\n  ~" + clientClass + "();"
				}
				assertBlockMatch("client.h class decl", got, golden, clientDeclStart, "~"+clientClass+"();")
				assertBlockMatch("client.h copy move", got, golden, "  ///@{\n  /// @name Copy and move support\n  "+clientClass+"("+clientClass+" const&) = default;", "  ///@}\n")
				assertBlockMatch("client.h equality", got, golden, "  ///@{\n  /// @name Equality\n  friend bool operator==("+clientClass+" const& a, "+clientClass+" const& b)", "  ///@}\n")
				assertBlockMatch("client.h private members", got, golden, " private:\n  std::shared_ptr<"+connClass+"> connection_;\n  Options options_;\n};", "};")
			}

			// 2. client.cc
			{
				got, golden := readGenAndGolden(ClientSourcePath(libCfg.ProductPath, svc))
				assertBlockMatch("client.cc constructor destructor", got, golden, clientClass+"::"+clientClass+"(\n    std::shared_ptr<"+connClass+"> connection, Options opts)\n    : connection_(std::move(connection)),", clientClass+"::~"+clientClass+"() = default;\n")
			}

			// 3. connection.h
			{
				got, golden := readGenAndGolden(ConnectionHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("connection.h retry policy", got, golden, "class "+retryPolicy+" : public ::google::cloud::RetryPolicy {", "};\n")
				assertBlockMatch("connection.h limited error count", got, golden, "class "+limitedErrorCount+" : public "+retryPolicy+" {", "};\n")
				assertBlockMatch("connection.h limited time", got, golden, "class "+limitedTime+" : public "+retryPolicy+" {", "};\n")
				assertBlockMatch("connection.h connection class", got, golden, "class "+connClass+" {\n public:\n  virtual ~"+connClass+"() = 0;\n\n  virtual Options options() { return Options{}; }\n", "virtual Options options() { return Options{}; }\n")
				assertBlockMatch("connection.h make connection", got, golden, "std::shared_ptr<"+connClass+"> Make"+connClass+"(\n    Options options = {});", "Options options = {});")
			}

			// 4. connection.cc
			{
				got, golden := readGenAndGolden(ConnectionSourcePath(libCfg.ProductPath, svc))
				assertBlockMatch("connection.cc destructor", got, golden, connClass+"::~"+connClass+"() = default;\n", connClass+"::~"+connClass+"() = default;\n")
			}

			// 5. connection_idempotency_policy.h
			{
				got, golden := readGenAndGolden(IdempotencyPolicyHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("connection_idempotency_policy.h class", got, golden, "class "+idempotencyClass+" {\n public:\n  virtual ~"+idempotencyClass+"();\n\n  /// Create a new copy of this object.\n  virtual std::unique_ptr<"+idempotencyClass+"> clone() const;", "clone() const;")
				assertBlockMatch("connection_idempotency_policy.h factory", got, golden, "std::unique_ptr<"+idempotencyClass+">\n    MakeDefault"+idempotencyClass+"();", "();")
			}

			// 6. connection_idempotency_policy.cc
			{
				got, golden := readGenAndGolden(IdempotencyPolicySourcePath(libCfg.ProductPath, svc))
				assertBlockMatch("connection_idempotency_policy.cc using", got, golden, "using ::google::cloud::Idempotency;\n", "using ::google::cloud::Idempotency;\n")
				assertBlockMatch("connection_idempotency_policy.cc destructor", got, golden, idempotencyClass+"::~"+idempotencyClass+"() = default;\n", idempotencyClass+"::~"+idempotencyClass+"() = default;\n")
				assertBlockMatch("connection_idempotency_policy.cc clone", got, golden, "std::unique_ptr<"+idempotencyClass+">\n"+idempotencyClass+"::clone() const {\n  return std::make_unique<"+idempotencyClass+">(*this);\n}", "}")
				assertBlockMatch("connection_idempotency_policy.cc factory", got, golden, "std::unique_ptr<"+idempotencyClass+">\n    MakeDefault"+idempotencyClass+"() {\n  return std::make_unique<"+idempotencyClass+">();\n}", "}")
			}

			// 7. options.h
			{
				got, golden := readGenAndGolden(OptionsHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("options.h retry option", got, golden, "struct "+retryPolicy+"Option {\n  using Type = std::shared_ptr<"+retryPolicy+">;\n};", "};")
				assertBlockMatch("options.h backoff option", got, golden, "struct "+svc+"BackoffPolicyOption {\n  using Type = std::shared_ptr<BackoffPolicy>;\n};", "};")
				assertBlockMatch("options.h idempotency option", got, golden, "struct "+idempotencyClass+"Option {\n  using Type = std::shared_ptr<"+idempotencyClass+">;\n};", "};")
				if tc.hasLRO {
					assertBlockMatch("options.h polling option", got, golden, "struct "+svc+"PollingPolicyOption {\n  using Type = std::shared_ptr<PollingPolicy>;\n};", "};")
					assertBlockMatch("options.h policy option list", got, golden, "using "+svc+"PolicyOptionList =\n    OptionList<"+retryPolicy+"Option,\n               "+svc+"BackoffPolicyOption,\n               "+svc+"PollingPolicyOption,\n               "+idempotencyClass+"Option>;", ">;")
				} else {
					assertBlockMatch("options.h policy option list", got, golden, "using "+svc+"PolicyOptionList =\n    OptionList<"+retryPolicy+"Option,\n               "+svc+"BackoffPolicyOption,\n               "+idempotencyClass+"Option>;", ">;")
				}
			}

			// 8. mock_connection.h
			{
				got, golden := readGenAndGolden(MockConnectionHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("mock_connection.h class", got, golden, "class "+mockConnClass+" : public "+tc.ns+"::"+connClass+" {\n public:\n  MOCK_METHOD(Options, options, (), (override));\n", "MOCK_METHOD(Options, options, (), (override));\n")
			}

			// 9. retry_traits.h
			{
				got, golden := readGenAndGolden(RetryTraitsHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("retry_traits.h struct", got, golden, "struct "+retryTraits+" {\n  static bool IsPermanentFailure(google::cloud::Status const& status) {", "}")
			}

			// 10. option_defaults.h
			{
				got, golden := readGenAndGolden(OptionDefaultsHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("option_defaults.h decl", got, golden, "Options "+svc+"DefaultOptions(Options options);", ";")
			}

			// 11. connection_impl.h
			{
				got, golden := readGenAndGolden(ConnectionImplHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("connection_impl.h class", got, golden, "class "+connImplClass+"\n    : public "+tc.ns+"::"+connClass+" {\n public:\n  ~"+connImplClass+"() override = default;", "~"+connImplClass+"() override = default;")
				assertBlockMatch("connection_impl.h constructor", got, golden, "  "+connImplClass+"(\n    std::unique_ptr<google::cloud::BackgroundThreads> background,\n    std::shared_ptr<"+tc.internalNs+"::"+stubClass+"> stub,\n    Options options);", "options);")
				assertBlockMatch("connection_impl.h options", got, golden, "  Options options() override { return options_; }\n", "options_; }\n")
				connImplPrivate := " private:\n  std::unique_ptr<google::cloud::BackgroundThreads> background_;\n  std::shared_ptr<" + tc.internalNs + "::" + stubClass + "> stub_;\n  Options options_;\n};"
				if tc.hasRequestId {
					connImplPrivate = " private:\n  std::unique_ptr<google::cloud::BackgroundThreads> background_;\n  std::shared_ptr<" + tc.internalNs + "::" + stubClass + "> stub_;\n  Options options_;\n  std::shared_ptr<google::cloud::internal::InvocationIdGenerator>\n      invocation_id_generator_ =\n          std::make_shared<google::cloud::internal::InvocationIdGenerator>();\n};"
				}
				assertBlockMatch("connection_impl.h private members", got, golden, connImplPrivate, "};")
			}

			// 12. stub.h
			{
				got, golden := readGenAndGolden(StubHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("stub.h stub class", got, golden, "class "+stubClass+" {\n public:\n  virtual ~"+stubClass+"() = 0;", "virtual ~"+stubClass+"() = 0;")
				assertBlockMatch("stub.h default stub class", got, golden, "class "+defaultStubClass+" : public "+stubClass+" {", stubClass+" {")
			}

			// 13. stub.cc
			{
				got, golden := readGenAndGolden(StubSourcePath(libCfg.ProductPath, svc))
				assertBlockMatch("stub.cc destructor", got, golden, stubClass+"::~"+stubClass+"() = default;\n", stubClass+"::~"+stubClass+"() = default;\n")
			}

			// 14. stub_factory.h
			{
				got, golden := readGenAndGolden(StubFactoryHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("stub_factory.h decl", got, golden, "std::shared_ptr<"+stubClass+"> CreateDefault"+stubClass+"(\n    std::shared_ptr<internal::GrpcAuthenticationStrategy> auth,\n    Options const& options);", ");")
			}

			// 15. auth_decorator.h
			{
				got, golden := readGenAndGolden(AuthDecoratorHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("auth_decorator.h class", got, golden, "class "+authClass+" : public "+stubClass+" {\n public:\n  ~"+authClass+"() override = default;\n  "+authClass+"(\n      std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,\n      std::shared_ptr<"+stubClass+"> child);", "child);")
				assertBlockMatch("auth_decorator.h private members", got, golden, " private:\n  std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth_;\n  std::shared_ptr<"+stubClass+"> child_;\n};", "};")
			}

			// 16. logging_decorator.h
			{
				got, golden := readGenAndGolden(LoggingDecoratorHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("logging_decorator.h class", got, golden, "class "+loggingClass+" : public "+stubClass+" {\n public:\n  ~"+loggingClass+"() override = default;\n  "+loggingClass+"(std::shared_ptr<"+stubClass+"> child,\n                       TracingOptions tracing_options,\n                       std::set<std::string> const& components);", "components);")
				loggingPrivateMembers := " private:\n  std::shared_ptr<" + stubClass + "> child_;\n  TracingOptions tracing_options_;\n};  // " + loggingClass
				if tc.hasStreaming {
					loggingPrivateMembers = " private:\n  std::shared_ptr<" + stubClass + "> child_;\n  TracingOptions tracing_options_;\n  bool stream_logging_;\n};  // " + loggingClass
				}
				assertBlockMatch("logging_decorator.h private members", got, golden, loggingPrivateMembers, loggingClass)
			}

			// 17. metadata_decorator.h
			{
				got, golden := readGenAndGolden(MetadataDecoratorHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("metadata_decorator.h class", got, golden, "class "+metadataClass+" : public "+stubClass+" {\n public:\n  ~"+metadataClass+"() override = default;\n  "+metadataClass+"(\n      std::shared_ptr<"+stubClass+"> child,\n      std::multimap<std::string, std::string> fixed_metadata,\n      std::string api_client_header = \"\");", "api_client_header = \"\");")
				assertBlockMatch("metadata_decorator.h set metadata", got, golden, "  void SetMetadata(grpc::ClientContext& context,\n                   Options const& options,\n                   std::string const& request_params);\n  void SetMetadata(grpc::ClientContext& context, Options const& options);", "Options const& options);")
				assertBlockMatch("metadata_decorator.h private members", got, golden, "  std::shared_ptr<"+stubClass+"> child_;\n  std::multimap<std::string, std::string> fixed_metadata_;\n  std::string api_client_header_;\n};", "};")
			}

			// 18. tracing_connection.h
			{
				got, golden := readGenAndGolden(TracingConnectionHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("tracing_connection.h class", got, golden, "#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY\n\nclass "+tracingConnClass+"\n    : public "+tc.ns+"::"+connClass+" {\n public:\n  ~"+tracingConnClass+"() override = default;\n\n  explicit "+tracingConnClass+"(\n    std::shared_ptr<"+tc.ns+"::"+connClass+"> child);\n\n  Options options() override { return child_->options(); }", "child_->options(); }")
				assertBlockMatch("tracing_connection.h private members", got, golden, " private:\n  std::shared_ptr<"+tc.ns+"::"+connClass+"> child_;\n};\n\n#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY", "#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY")
				assertBlockMatch("tracing_connection.h factory", got, golden, "std::shared_ptr<"+tc.ns+"::"+connClass+">\nMake"+tracingConnClass+"(\n    std::shared_ptr<"+tc.ns+"::"+connClass+"> conn);", "conn);")
			}

			// 19. tracing_stub.h
			{
				got, golden := readGenAndGolden(TracingStubHeaderPath(libCfg.ProductPath, svc))
				assertBlockMatch("tracing_stub.h class", got, golden, "#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY\n\nclass "+tracingStubClass+" : public "+stubClass+" {\n public:\n  ~"+tracingStubClass+"() override = default;\n\n  explicit "+tracingStubClass+"(std::shared_ptr<"+stubClass+"> child);", "child);")
				assertBlockMatch("tracing_stub.h private members", got, golden, " private:\n  std::shared_ptr<"+stubClass+"> child_;\n  std::shared_ptr<opentelemetry::context::propagation::TextMapPropagator> propagator_;\n};\n\n#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY", "#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY")
				assertBlockMatch("tracing_stub.h factory", got, golden, "std::shared_ptr<"+stubClass+"> Make"+tracingStubClass+"(\n    std::shared_ptr<"+stubClass+"> stub);", "stub);")
			}
		})
	}
}

func TestGenerate_ForwardingHeaders(t *testing.T) {
	requireProtoc(t)

	srcs := &sources.Sources{
		Googleapis:  filepath.Join("..", "..", "testdata", "googleapis"),
		ProtobufSrc: filepath.Join("testdata", "protos"),
	}
	sourceConfig := &sources.SourceConfig{
		Sources:     srcs,
		ActiveRoots: []string{"protobuf-src", "googleapis"},
		IncludeList: []string{"test.proto", "backup.proto"},
	}
	modelConfig := &parser.ModelConfig{
		Language:            config.LanguageCpp,
		SpecificationFormat: config.SpecProtobuf,
		SpecificationSource: "generator/integration_tests",
		ServiceConfig:       "generator/integration_tests/test.yaml",
		Source:              sourceConfig,
	}

	model, err := parser.CreateModel(modelConfig)
	if err != nil {
		t.Fatal(err)
	}
	if err := api.Validate(model); err != nil {
		t.Fatal(err)
	}

	for _, test := range []struct {
		serviceName string
	}{
		{serviceName: "GoldenKitchenSink"},
		{serviceName: "GoldenThingAdmin"},
	} {
		t.Run(test.serviceName, func(t *testing.T) {
			outdir := t.TempDir()

			libCfg := &config.CppLibrary{
				ProductPath:                   "generator/integration_tests/golden/v1",
				ForwardingProductPath:         "generator/integration_tests/golden",
				InitialCopyrightYear:          "2022",
				OverrideServiceConfigYAMLName: "generator/integration_tests/test.yaml",
			}

			if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
				t.Fatal(err)
			}

			fwdFiles := ForwardingGeneratedFiles(libCfg.ForwardingProductPath, test.serviceName)
			if len(fwdFiles) != 5 {
				t.Fatalf("expected 5 forwarding files, got %d", len(fwdFiles))
			}

			goldenDir := filepath.Join("testdata", "golden")
			prefix := libCfg.ForwardingProductPath + "/"

			for _, gen := range fwdFiles {
				t.Run(gen.OutputPath, func(t *testing.T) {
					fullPath := filepath.Join(outdir, gen.OutputPath)
					content, err := os.ReadFile(fullPath)
					if err != nil {
						t.Fatalf("missing expected forwarding file %q: %v", gen.OutputPath, err)
					}
					got := string(content)

					relPath := strings.TrimPrefix(gen.OutputPath, prefix)
					goldenPath := filepath.Join(goldenDir, relPath)
					goldenContentBytes, err := os.ReadFile(goldenPath)
					if err != nil {
						t.Fatalf("missing golden file %q: %v", goldenPath, err)
					}
					golden := string(goldenContentBytes)

					guard := FormatHeaderIncludeGuard(gen.OutputPath)

					// Compare full header block from guard open to guard close (includes, namespaces, aliases).
					gotBlock := extractBlock(t, got, "#ifndef "+guard, "#endif  // "+guard+"\n")
					wantBlock := extractBlock(t, golden, "#ifndef "+guard, "#endif  // "+guard+"\n")
					if diff := cmp.Diff(wantBlock, gotBlock); diff != "" {
						t.Logf("file %s full header block mismatch", gen.OutputPath)
						t.Errorf("mismatch (-want +got):\n%s", diff)
					}

					// Also explicitly compare the forwarding aliases inside inline namespace.
					gotAliases := extractBlock(t, got, "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN\n", "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END\n")
					wantAliases := extractBlock(t, golden, "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN\n", "GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END\n")
					if diff := cmp.Diff(wantAliases, gotAliases); diff != "" {
						t.Logf("file %s forwarding aliases mismatch", gen.OutputPath)
						t.Errorf("mismatch (-want +got):\n%s", diff)
					}
				})
			}
		})
	}
}

func TestGenerate_OutputContainment_Error(t *testing.T) {
	for _, test := range []struct {
		name    string
		libCfg  *config.CppLibrary
		wantErr error
	}{
		{
			name: "escaping product path parent traversal",
			libCfg: &config.CppLibrary{
				ProductPath: "../escaped",
			},
			wantErr: ErrEscapesOutputDirectory,
		},
		{
			name: "escaping product path root traversal",
			libCfg: &config.CppLibrary{
				ProductPath: "..",
			},
			wantErr: ErrEscapesOutputDirectory,
		},
		{
			name: "deep escaping product path",
			libCfg: &config.CppLibrary{
				ProductPath: "sub/../../escaped",
			},
			wantErr: ErrEscapesOutputDirectory,
		},
		{
			name: "escaping forwarding product path",
			libCfg: &config.CppLibrary{
				ProductPath:           "v1",
				ForwardingProductPath: "../forwarding_escaped",
			},
			wantErr: ErrEscapesOutputDirectory,
		},
		{
			name: "duplicate output path between service and forwarding",
			libCfg: &config.CppLibrary{
				ProductPath:           "v1",
				ForwardingProductPath: "v1",
			},
			wantErr: ErrDuplicateOutputPath,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outdir := t.TempDir()
			svc := api.NewTestService("SimpleService")
			model := api.NewTestAPI(nil, nil, []*api.Service{svc})

			err := Generate(t.Context(), model, outdir, test.libCfg)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !errors.Is(err, test.wantErr) {
				t.Errorf("expected error wrapping %v, got %v", test.wantErr, err)
			}
		})
	}
}

func TestGenerate_OmittedServices(t *testing.T) {
	outdir := t.TempDir()
	svc1 := api.NewTestService("ActiveService")
	svc2 := api.NewTestService("OmittedService")
	model := api.NewTestAPI(nil, nil, []*api.Service{svc1, svc2})

	libCfg := &config.CppLibrary{
		ProductPath:     "v1",
		OmittedServices: []string{"OmittedService"},
	}

	if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
		t.Fatal(err)
	}

	activeFiles := ServiceGeneratedFiles("v1", "ActiveService")
	for _, f := range activeFiles {
		if _, err := os.Stat(filepath.Join(outdir, f.OutputPath)); err != nil {
			t.Errorf("expected active service file %q to exist: %v", f.OutputPath, err)
		}
	}

	omittedFiles := ServiceGeneratedFiles("v1", "OmittedService")
	for _, f := range omittedFiles {
		if _, err := os.Stat(filepath.Join(outdir, f.OutputPath)); !errors.Is(err, fs.ErrNotExist) {
			t.Errorf("expected omitted service file %q not to exist", f.OutputPath)
		}
	}
}

func TestGenerate_GrpcDisabled(t *testing.T) {
	outdir := t.TempDir()
	svc := api.NewTestService("RestOnlyService")
	model := api.NewTestAPI(nil, nil, []*api.Service{svc})

	disabled := false
	libCfg := &config.CppLibrary{
		ProductPath:           "v1",
		GenerateGrpcTransport: &disabled,
	}

	if err := Generate(t.Context(), model, outdir, libCfg); err != nil {
		t.Fatal(err)
	}

	// CMakeLists should still exist.
	if _, err := os.Stat(filepath.Join(outdir, "CMakeLists.txt")); err != nil {
		t.Errorf("CMakeLists.txt should exist: %v", err)
	}

	// No service files should exist.
	svcFiles := ServiceGeneratedFiles("v1", "RestOnlyService")
	for _, f := range svcFiles {
		if _, err := os.Stat(filepath.Join(outdir, f.OutputPath)); !errors.Is(err, fs.ErrNotExist) {
			t.Errorf("expected gRPC file %q not to exist when gRPC is disabled", f.OutputPath)
		}
	}
}

func TestServiceGeneratedFilesMatchGolden(t *testing.T) {
	for _, test := range []struct {
		name        string
		serviceName string
	}{
		{
			name:        "RequestIdService",
			serviceName: "RequestIdService",
		},
		{
			name:        "DeprecatedService",
			serviceName: "DeprecatedService",
		},
		{
			name:        "GoldenKitchenSink",
			serviceName: "GoldenKitchenSink",
		},
		{
			name:        "GoldenThingAdmin",
			serviceName: "GoldenThingAdmin",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			files := ServiceGeneratedFiles("", test.serviceName)
			goldenV1 := filepath.Join("testdata", "golden", "v1")

			for _, f := range files {
				goldenPath := filepath.Join(goldenV1, f.OutputPath)
				if _, err := os.Stat(goldenPath); err != nil {
					t.Errorf("file %q not found in golden files: %v", f.OutputPath, err)
				}
			}
		})
	}
}

func TestForwardingGeneratedFilesMatchGolden(t *testing.T) {
	for _, test := range []struct {
		name        string
		serviceName string
	}{
		{
			name:        "GoldenKitchenSink",
			serviceName: "GoldenKitchenSink",
		},
		{
			name:        "GoldenThingAdmin",
			serviceName: "GoldenThingAdmin",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			files := ForwardingGeneratedFiles("", test.serviceName)
			goldenRoot := filepath.Join("testdata", "golden")

			for _, f := range files {
				goldenPath := filepath.Join(goldenRoot, f.OutputPath)
				if _, err := os.Stat(goldenPath); err != nil {
					t.Errorf("forwarding file %q not found in golden files: %v", f.OutputPath, err)
				}
			}
		})
	}
}

func TestExtractBlock(t *testing.T) {
	for _, test := range []struct {
		name        string
		content     string
		startMarker string
		endMarker   string
		want        string
	}{
		{
			name:        "basic block extraction",
			content:     "before\nSTART\nmiddle\nEND\nafter",
			startMarker: "START",
			endMarker:   "END",
			want:        "START\nmiddle\nEND",
		},
		{
			name:        "end marker before start marker is ignored",
			content:     "END\nbefore\nSTART\nmiddle\nEND\nafter",
			startMarker: "START",
			endMarker:   "END",
			want:        "START\nmiddle\nEND",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			got := extractBlock(t, test.content, test.startMarker, test.endMarker)
			if diff := cmp.Diff(test.want, got); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

// extractBlock extracts the text between startStr and endStr (inclusive).
// If either marker is not found, it fails the test with t.Fatalf,
// matching internal/sidekick/swift/generate_package_swift_test.go.
func extractBlock(t *testing.T, content, startStr, endStr string) string {
	t.Helper()
	startIdx := strings.Index(content, startStr)
	if startIdx == -1 {
		t.Fatalf("missing expected block start %q\n\n%s", startStr, content)
	}
	endIdx := strings.Index(content[startIdx:], endStr)
	if endIdx == -1 {
		t.Fatalf("missing expected block end %q\n\n%s", endStr, content)
	}
	return content[startIdx : startIdx+endIdx+len(endStr)]
}
