// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
	"github.com/googleapis/librarian/internal/sidekick/language"
)

func TestGenerate_CMakeLists(t *testing.T) {
	for _, test := range []struct {
		name     string
		lib      *config.CppLibrary
		wantYear string
	}{
		{
			name:     "default copyright year",
			lib:      nil,
			wantYear: "2026",
		},
		{
			name: "custom copyright year",
			lib: &config.CppLibrary{
				InitialCopyrightYear: "2021",
			},
			wantYear: "2021",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outdir := t.TempDir()
			model := api.NewTestAPI(
				[]*api.Message{api.NewTestMessage("Item")},
				nil,
				[]*api.Service{api.NewTestService("ItemsService")},
			)
			if err := Generate(t.Context(), model, outdir, test.lib); err != nil {
				t.Fatalf("Generate failed: %v", err)
			}
			cmakePath := filepath.Join(outdir, "CMakeLists.txt")
			content, err := os.ReadFile(cmakePath)
			if err != nil {
				t.Fatalf("failed to read generated CMakeLists.txt: %v", err)
			}
			s := string(content)
			if !strings.Contains(s, "# Generated by the Codegen C++ plugin.") {
				t.Errorf("CMakeLists.txt missing banner, got:\n%s", s)
			}
			expectedCopyright := "# Copyright " + test.wantYear + " Google LLC"
			if !strings.Contains(s, expectedCopyright) {
				t.Errorf("CMakeLists.txt missing expected copyright %q, got:\n%s", expectedCopyright, s)
			}
			if !strings.Contains(s, "Licensed under the Apache License, Version 2.0") {
				t.Errorf("CMakeLists.txt missing license text, got:\n%s", s)
			}
		})
	}
}

func TestValidateOutputContainment(t *testing.T) {
	outdir := t.TempDir()
	for _, test := range []struct {
		name    string
		files   []language.GeneratedFile
		wantErr bool
	}{
		{
			name: "valid relative output path",
			files: []language.GeneratedFile{
				{OutputPath: "CMakeLists.txt"},
				{OutputPath: "include/google/cloud/service.h"},
			},
			wantErr: false,
		},
		{
			name: "valid relative output path with leading slash",
			files: []language.GeneratedFile{
				{OutputPath: "/CMakeLists.txt"},
				{OutputPath: "/include/google/cloud/service.h"},
			},
			wantErr: false,
		},
		{
			name: "escaping path with parent traversal",
			files: []language.GeneratedFile{
				{OutputPath: "../escaped.txt"},
			},
			wantErr: true,
		},
		{
			name: "escaping root parent traversal",
			files: []language.GeneratedFile{
				{OutputPath: ".."},
			},
			wantErr: true,
		},
		{
			name: "deep escaping path",
			files: []language.GeneratedFile{
				{OutputPath: "sub/../../escaped.txt"},
			},
			wantErr: true,
		},
		{
			name: "escaping path with leading slash parent traversal",
			files: []language.GeneratedFile{
				{OutputPath: "/../escaped.txt"},
			},
			wantErr: true,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			err := validateOutputContainment(outdir, test.files)
			if (err != nil) != test.wantErr {
				t.Errorf("validateOutputContainment() error = %v, wantErr = %v", err, test.wantErr)
			}
		})
	}
}
