// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/command"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/license"
	"github.com/googleapis/librarian/internal/sources"
)

const gRPCFileStart = "// DO NOT EDIT.\n// swift-format-ignore-file"

func compileProtobufs(ctx context.Context, library *config.Library, module *config.SwiftModule, src *sources.Sources) error {
	if err := os.MkdirAll(module.Output, 0755); err != nil {
		return err
	}

	sourceConfig := sources.NewSourceConfig(src, library.Roots)
	apiPathAbs := sourceConfig.ResolveDir(module.APIPath)

	var protoFiles []string
	if len(module.IncludeList) > 0 {
		for _, file := range module.IncludeList {
			protoFiles = append(protoFiles, filepath.Join(apiPathAbs, file))
		}
	} else {
		entries, err := os.ReadDir(apiPathAbs)
		if err != nil {
			return err
		}
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".proto") {
				protoFiles = append(protoFiles, filepath.Join(apiPathAbs, entry.Name()))
			}
		}
	}

	if len(protoFiles) == 0 {
		return fmt.Errorf("no proto files found in %s", apiPathAbs)
	}

	importsMap := make(map[string]bool)
	var protoImports []string

	addImport := func(path string) {
		if path != "" && !importsMap[path] {
			importsMap[path] = true
			protoImports = append(protoImports, "-I", path)
		}
	}

	for _, r := range sourceConfig.ActiveRoots {
		addImport(sourceConfig.Root(r))
	}

	args := []string{
		"--swift_out=Visibility=Public:" + module.Output,
		"--grpc-swift_out=Visibility=Public:" + module.Output,
	}
	args = append(args, protoImports...)
	args = append(args, protoFiles...)

	if err := command.Run(ctx, "protoc", args...); err != nil {
		return err
	}

	return addCopyrightCommentsToGrpc(module, library)
}

// addCopyrightCommentsToGrpc finds all the gRPC-generated files for `module` and adds
// the copyright boilerplate to them.
//
// The gRPC plugin does not add copyright boilerplate to the generated code. A
// (maybe overly) strict interpretation of the Google policies for OSS is that
// all files that can have copyright notices should have such notices.
//
// This function finds all the files generated by the gRPC plugin and adds the
// notice. It is only called from `computeProtobufs()`, we split it to keep the
// functions small-ish.
func addCopyrightCommentsToGrpc(module *config.SwiftModule, library *config.Library) error {
	bp := copyrightComments(library.CopyrightYear)
	return filepath.WalkDir(module.Output, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".grpc.swift") {
			return err
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		got := contents[0:min(len(bp), len(contents))]
		if bytes.Equal(bp, got) {
			return nil
		}
		newContents := append(bp, contents...)
		return os.WriteFile(path, newContents, 0644)
	})
}

func copyrightComments(year string) []byte {
	want := fmt.Appendf(nil, "%s\n", gRPCFileStart)
	for _, t := range license.Header(year) {
		want = fmt.Appendf(want, "//%s\n", t)
	}
	return want
}
