// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerateReadme_ServiceLibrary(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.secretmanager.v1"
	inputType := api.NewTestMessage("Request").
		WithPackage(pkg).
		WithFields(api.NewTestField("name").WithType(api.TypezString))
	outputType := api.NewTestMessage("Response").
		WithPackage(pkg).
		WithFields(api.NewTestField("value").WithType(api.TypezString))
	method := api.NewTestMethod("GetSecret").
		WithInput(inputType).
		WithOutput(outputType).
		WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
	service := api.NewTestService("SecretManagerService").
		WithPackage(pkg).
		WithMethods(method)
	model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service}).
		WithPackageName(pkg).
		WithTitle("Secret Manager API").
		WithDescription("Stores sensitive data such as API keys, passwords, and certificates.")

	library := &config.Library{
		Name:    "google-cloud-secretmanager-v1",
		Version: "0.1.0-preview",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	readmePath := filepath.Join(outDir, "README.md")
	contentBytes, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	want := `# Google Cloud Client Libraries for Swift - Secret Manager API

<!-- Code generated by sidekick. DO NOT EDIT. -->

[![Swift Compatibility](https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2Fapi%2Fpackages%2Fgoogleapis%2Fswift-google-cloud-secretmanager-v1%2Fbadge%3Ftype%3Dswift-versions)](https://swiftpackageindex.com/googleapis/swift-google-cloud-secretmanager-v1)
[![Platform Compatibility](https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2Fapi%2Fpackages%2Fgoogleapis%2Fswift-google-cloud-secretmanager-v1%2Fbadge%3Ftype%3Dplatforms)](https://swiftpackageindex.com/googleapis/swift-google-cloud-secretmanager-v1)

Stores sensitive data such as API keys, passwords, and certificates.

## Overview

Most applications use the ` + "`*Client`" + ` types in this library:

- ` + "`SecretManagerServiceClient`: Client for the SecretManagerService." + `

## Quickstart

The following example demonstrates using ` + "`SecretManagerServiceClient`:" + `

` + "```swift" + `
import Foundation
import GoogleCloudSecretmanagerV1

func sample() async throws {
  let client = try GoogleCloudSecretmanagerV1.SecretManagerServiceClient()
  print("use ` + "`client`" + ` to make requests: \(client)")
}
` + "```" + `

## Requirements

For the minimum supported Swift version and platform requirements, see the
[Requirements](https://github.com/googleapis/google-cloud-swift#minimum-supported-swift-version)
section in the ` + "`google-cloud-swift`" + ` repository.

## Installation

Add ` + "`swift-google-cloud-secretmanager-v1`" + ` as a package dependency:

` + "```bash" + `
swift package add-dependency https://github.com/googleapis/swift-google-cloud-secretmanager-v1.git --from 0.1.0-preview
` + "```" + `

Then add ` + "`GoogleCloudSecretmanagerV1`" + ` to your target's dependencies:

` + "```bash" + `
swift package add-target-dependency GoogleCloudSecretmanagerV1 <target-name> --package swift-google-cloud-secretmanager-v1
` + "```" + `

## Troubleshooting

For questions, bug reports, or feature requests, please open an issue in the
[google-cloud-swift](https://github.com/googleapis/google-cloud-swift/issues) repository.

## Contributing

Contributions to this library are always welcome and highly encouraged.

All development, issues, and pull requests are managed in the
[google-cloud-swift](https://github.com/googleapis/google-cloud-swift) monorepo.
See [CONTRIBUTING.md](https://github.com/googleapis/google-cloud-swift/blob/main/CONTRIBUTING.md)
for details on getting started.

## License

Apache 2.0 - See [LICENSE](LICENSE) for more information.
`
	if diff := cmp.Diff(want, content); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}

func TestGenerateReadme_WithTraits(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.example.v1"
	inputType := api.NewTestMessage("Request").
		WithPackage(pkg).
		WithFields(api.NewTestField("name").WithType(api.TypezString))
	outputType := api.NewTestMessage("Response").
		WithPackage(pkg).
		WithFields(api.NewTestField("value").WithType(api.TypezString))
	method := api.NewTestMethod("Get").
		WithInput(inputType).
		WithOutput(outputType).
		WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
	service := api.NewTestService("Service").
		WithPackage(pkg).
		WithMethods(method)
	service2 := api.NewTestService("OtherService").
		WithPackage(pkg).
		WithMethods(method)
	model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service, service2}).
		WithPackageName(pkg).
		WithTitle("Example API")

	cfg := swiftConfig(t, nil)
	cfg.PerServiceTraits = true
	cfg.DefaultTraits = []string{"Service"}
	library := &config.Library{
		Name:    "google-cloud-example-v1",
		Version: "1.0.0",
		Swift:   cfg,
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	contentBytes, err := os.ReadFile(filepath.Join(outDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	if !strings.Contains(content, "- `ServiceClient`: Client for the Service. (Recommended starting point) (enabled by the `Service` trait)") {
		t.Errorf("expected service to mention trait and recommended starting point, got:\n%s", content)
	}
	if !strings.Contains(content, "- `OtherServiceClient`: Client for the OtherService. (enabled by the `OtherService` trait)") {
		t.Errorf("expected other service to mention trait, got:\n%s", content)
	}

	wantTraitsSection := `### Package Traits

This package uses Swift package traits to conditionally compile individual service
clients and their associated types. Enabling a trait enables the corresponding
client and all the request, response, and model types needed to use that client.

The following traits are enabled by default:
- ` + "`Service`" + `

To enable additional traits alongside the defaults, specify them in ` + "`Package.swift`:" + `

` + "```swift" + `
.package(url: "https://github.com/googleapis/swift-google-cloud-example-v1.git", from: "1.0.0", traits: [".defaults", "<TraitName>"])
` + "```" + `

| Trait | Default | Enabled Client |
|---|:---:|---|
| ` + "`OtherService`" + ` | No | ` + "`OtherServiceClient`" + ` |
| ` + "`Service`" + ` | Yes | ` + "`ServiceClient`" + ` |
`

	if !strings.Contains(content, wantTraitsSection) {
		t.Errorf("expected package traits section in README.md, got:\n%s", content)
	}
}

func TestGenerateReadme_TypeOnlyLibrary(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.type"
	message := api.NewTestMessage("Color").
		WithPackage(pkg).
		WithFields(api.NewTestField("red").WithType(api.TypezFloat))
	model := api.NewTestAPI([]*api.Message{message}, nil, nil).
		WithPackageName(pkg).
		WithTitle("Google Type")

	library := &config.Library{
		Name:    "google-type",
		Version: "0.1.0-preview",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	readmePath := filepath.Join(outDir, "README.md")
	contentBytes, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	if !strings.Contains(content, "https://swiftpackageindex.com/googleapis/swift-google-type") {
		t.Errorf("expected SPI shields in README.md, got:\n%s", content)
	}

	wantOverview := `## Overview

This is a type-only library containing a collection of common types used by other
Google Cloud packages. It does not contain client types to make RPCs.`

	if !strings.Contains(content, wantOverview) {
		t.Errorf("expected type-only overview, got:\n%s", content)
	}

	if !strings.Contains(content, "swift package add-dependency https://github.com/googleapis/swift-google-type.git --from 0.1.0-preview") {
		t.Errorf("expected installation add-dependency command, got:\n%s", content)
	}
	if !strings.Contains(content, "swift package add-target-dependency GoogleType <target-name> --package swift-google-type") {
		t.Errorf("expected installation add-target-dependency command, got:\n%s", content)
	}
}

func TestGenerateReadme_WithRevision(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.compute.v1"
	message := api.NewTestMessage("Instance").
		WithPackage(pkg)
	model := api.NewTestAPI([]*api.Message{message}, nil, nil).
		WithPackageName(pkg).
		WithTitle("Compute Engine API")
	model.Revision = "20260101"

	library := &config.Library{
		Name:    "google-cloud-compute-v1",
		Version: "0.1.0",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	contentBytes, err := os.ReadFile(filepath.Join(outDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	wantRevision := `This client library was generated from the "20260101" revision of the API.`
	if !strings.Contains(content, wantRevision) {
		t.Errorf("expected revision text, got:\n%s", content)
	}
}
