// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerateLandingPage(t *testing.T) {
	basicConfig := swiftConfig(t, nil)
	perServiceConfig := swiftConfig(t, nil)
	perServiceConfig.PerServiceTraits = true

	for _, test := range []struct {
		name           string
		cfg            *config.SwiftPackage
		wantClientLink string
		hasTraits      bool
	}{
		{"basic", basicConfig, "- ``ServiceClient``\n", false},
		{"perService", perServiceConfig, "- ``ServiceClient``: enabled by the `Service` trait.\n", true},
	} {
		t.Run(test.name, func(t *testing.T) {
			outDir := t.TempDir()
			inputType := api.NewTestMessage("Request").
				WithFields(api.NewTestField("key").WithType(api.TypezString))
			outputType := api.NewTestMessage("Response").
				WithFields(api.NewTestField("value").WithType(api.TypezString))
			method := api.NewTestMethod("Get").
				WithInput(inputType).
				WithOutput(outputType).
				WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
			service := api.NewTestService("Service").WithMethods(method)
			model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service}).
				WithPackageName("test").
				WithTitle("Test Only API").
				WithDescription("The test API description\n--end description--\n")

			library := &config.Library{
				Name:    "test",
				Version: "0.1.0-preview",
				Swift:   test.cfg,
			}
			if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
				t.Fatal(err)
			}
			landing := filepath.Join(outDir, "Sources", "Test", "Test.docc", "Index.md")
			contentBytes, err := os.ReadFile(landing)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := os.Stat(filepath.Join(outDir, "Sources", "Test", "Test.docc", "Test.md")); !os.IsNotExist(err) {
				t.Errorf("expected Test.md to not exist, got %v", err)
			}
			content := string(contentBytes)

			got := extractBlock(t, content, "- ``ServiceClient``", "\n")
			if diff := cmp.Diff(test.wantClientLink, got); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}

			packageTraitsPath := filepath.Join(outDir, "Sources", "Test", "Test.docc", "PackageTraits.md")
			if test.hasTraits {
				if !strings.Contains(content, "## See Also\n\n- <doc:PackageTraits>\n") {
					t.Errorf("expected Index.md to contain See Also link to PackageTraits, got:\n%s", content)
				}
				traitsBytes, err := os.ReadFile(packageTraitsPath)
				if err != nil {
					t.Fatalf("expected PackageTraits.md to exist: %v", err)
				}
				traitsContent := string(traitsBytes)
				wantTraitsContent := `# Package Traits
<!-- Code generated by sidekick. DO NOT EDIT. -->

This package uses Swift package traits to conditionally compile individual service
clients and their associated types. Enabling a trait enables the corresponding
client and all the request, response, and model types needed to use that client.

No traits are enabled by default. Specify the traits you need in ` + "`Package.swift`:" + `

` + "```swift" + `
.package(url: "https://github.com/googleapis/swift-test.git", from: "0.1.0-preview", traits: ["<TraitName>"])
` + "```" + `

| Trait | Default | Enabled Client |
|---|:---:|---|
| ` + "`Service`" + ` | No | ` + "``ServiceClient``" + ` |
`
				if diff := cmp.Diff(wantTraitsContent, traitsContent); diff != "" {
					t.Errorf("PackageTraits.md mismatch (-want +got):\n%s", diff)
				}
			} else {
				if strings.Contains(content, "PackageTraits") {
					t.Errorf("expected Index.md to not mention PackageTraits when traits disabled")
				}
				if _, err := os.Stat(packageTraitsPath); !os.IsNotExist(err) {
					t.Errorf("expected PackageTraits.md to not exist, got %v", err)
				}
			}

			// verify other output that does not depend on the configuration.
			got = extractBlock(t, content, "# ``Test``", "--end description--\n")
			want := `# ` + "``Test``" + `
<!-- Code generated by sidekick. DO NOT EDIT. -->

The test API description
--end description--
`
			if diff := cmp.Diff(want, got); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}
