// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerateReadme_ServiceLibrary(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.secretmanager.v1"
	inputType := api.NewTestMessage("Request").
		WithPackage(pkg).
		WithFields(api.NewTestField("name").WithType(api.TypezString))
	outputType := api.NewTestMessage("Response").
		WithPackage(pkg).
		WithFields(api.NewTestField("value").WithType(api.TypezString))
	method := api.NewTestMethod("GetSecret").
		WithInput(inputType).
		WithOutput(outputType).
		WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
	service := api.NewTestService("SecretManagerService").
		WithPackage(pkg).
		WithMethods(method)
	model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service})
	model.PackageName = pkg
	model.Title = "Secret Manager API"
	model.Description = "Stores sensitive data such as API keys, passwords, and certificates."

	library := &config.Library{
		Name:    "google-cloud-secretmanager-v1",
		Version: "0.1.0-preview",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	readmePath := filepath.Join(outDir, "README.md")
	contentBytes, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	want := `# Google Cloud Client Libraries for Swift - Secret Manager API

<!-- Code generated by sidekick. DO NOT EDIT. -->

Stores sensitive data such as API keys, passwords, and certificates.

## Overview

Most applications use the ` + "`*Client`" + ` types in this library. A default initialized
client will let you interact with the API. The methods in the client type
correspond to RPCs in the API. Many APIs have more than one client, exposing
different aspects of the API, consult the reference documentation for details.

- ` + "`SecretManagerServiceClient`" + `

## Requirements

For the minimum supported Swift version and platform requirements, see the
[Requirements](https://github.com/googleapis/google-cloud-swift#minimum-supported-swift-version)
section in the ` + "`google-cloud-swift`" + ` repository.

## Installation

Add ` + "`swift-google-cloud-secretmanager-v1`" + ` as a package dependency:

` + "```bash" + `
swift package add-dependency https://github.com/googleapis/swift-google-cloud-secretmanager-v1.git --from 0.1.0-preview
` + "```" + `

Then add ` + "`GoogleCloudSecretmanagerV1`" + ` to your target's dependencies:

` + "```bash" + `
swift package add-target-dependency GoogleCloudSecretmanagerV1 <target-name> --package swift-google-cloud-secretmanager-v1
` + "```" + `

## Troubleshooting

For questions, bug reports, or feature requests, please open an issue in the
[google-cloud-swift](https://github.com/googleapis/google-cloud-swift/issues) repository.

## Contributing

Contributions to this library are always welcome and highly encouraged.

All development, issues, and pull requests are managed in the
[google-cloud-swift](https://github.com/googleapis/google-cloud-swift) monorepo.
See [CONTRIBUTING.md](https://github.com/googleapis/google-cloud-swift/blob/main/CONTRIBUTING.md)
for details on getting started.

## License

Apache 2.0 - See [LICENSE](LICENSE) for more information.
`
	if diff := cmp.Diff(want, content); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}

func TestGenerateReadme_WithTraits(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.example.v1"
	inputType := api.NewTestMessage("Request").
		WithPackage(pkg).
		WithFields(api.NewTestField("name").WithType(api.TypezString))
	outputType := api.NewTestMessage("Response").
		WithPackage(pkg).
		WithFields(api.NewTestField("value").WithType(api.TypezString))
	method := api.NewTestMethod("Get").
		WithInput(inputType).
		WithOutput(outputType).
		WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
	service := api.NewTestService("Service").
		WithPackage(pkg).
		WithMethods(method)
	model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service})
	model.PackageName = pkg
	model.Title = "Example API"

	cfg := swiftConfig(t, nil)
	cfg.PerServiceTraits = true
	library := &config.Library{
		Name:    "google-cloud-example-v1",
		Version: "1.0.0",
		Swift:   cfg,
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	contentBytes, err := os.ReadFile(filepath.Join(outDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	if !strings.Contains(content, "- `ServiceClient`: enabled by the `Service` trait.") {
		t.Errorf("expected service to mention trait, got:\n%s", content)
	}
}

func TestGenerateReadme_TypeOnlyLibrary(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.type"
	message := api.NewTestMessage("Color").
		WithPackage(pkg).
		WithFields(api.NewTestField("red").WithType(api.TypezFloat))
	model := api.NewTestAPI([]*api.Message{message}, nil, nil)
	model.PackageName = pkg
	model.Title = "Google Type"

	library := &config.Library{
		Name:    "google-type",
		Version: "0.1.0-preview",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	readmePath := filepath.Join(outDir, "README.md")
	contentBytes, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	wantOverview := `## Overview

This is a type-only library. You will not find functions to make RPCs in this
library. Its types are used in other libraries that access Google Cloud.`

	if !strings.Contains(content, wantOverview) {
		t.Errorf("expected type-only overview, got:\n%s", content)
	}

	if !strings.Contains(content, "swift package add-dependency https://github.com/googleapis/swift-google-type.git --from 0.1.0-preview") {
		t.Errorf("expected installation add-dependency command, got:\n%s", content)
	}
	if !strings.Contains(content, "swift package add-target-dependency GoogleType <target-name> --package swift-google-type") {
		t.Errorf("expected installation add-target-dependency command, got:\n%s", content)
	}
}

func TestGenerateReadme_WithRevision(t *testing.T) {
	outDir := t.TempDir()
	pkg := "google.cloud.compute.v1"
	message := api.NewTestMessage("Instance").
		WithPackage(pkg)
	model := api.NewTestAPI([]*api.Message{message}, nil, nil)
	model.PackageName = pkg
	model.Title = "Compute Engine API"
	model.Revision = "20260101"

	library := &config.Library{
		Name:    "google-cloud-compute-v1",
		Version: "0.1.0",
		Swift:   swiftConfig(t, nil),
	}
	if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
		t.Fatal(err)
	}

	contentBytes, err := os.ReadFile(filepath.Join(outDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(contentBytes)

	wantRevision := `This client library was generated from the "20260101" revision of the API.`
	if !strings.Contains(content, wantRevision) {
		t.Errorf("expected revision text, got:\n%s", content)
	}
}
