// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerateSpiYml(t *testing.T) {
	for _, test := range []struct {
		name        string
		libraryName string
		override    string
		wantTarget  string
	}{
		{
			name:        "default derived library name",
			libraryName: "google-cloud-workflows-v1",
			wantTarget:  "GoogleCloudWorkflowsV1",
		},
		{
			name:        "overridden library name",
			libraryName: "google-cloud-secretmanager-v1",
			override:    "CustomSecretManagerTarget",
			wantTarget:  "CustomSecretManagerTarget",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outDir := t.TempDir()
			service := api.NewTestService("Workflows").WithPackage("google.cloud.workflows.v1")
			model := api.NewTestAPI(nil, nil, []*api.Service{service})
			model.PackageName = "google.cloud.workflows.v1"

			cfg := swiftConfig(t, nil)
			if test.override != "" {
				cfg.LibraryNameOverride = test.override
			}
			library := &config.Library{
				Name:          test.libraryName,
				CopyrightYear: "2026",
				Swift:         cfg,
			}
			if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
				t.Fatal(err)
			}

			spiYmlPath := filepath.Join(outDir, ".spi.yml")
			content, err := os.ReadFile(spiYmlPath)
			if err != nil {
				t.Fatal(err)
			}

			want := fmt.Sprintf(`# Code generated by sidekick. DO NOT EDIT.
#
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 1
builder:
  configs:
    - platform: macos-spm
      documentation_targets:
        - %s
    - platform: linux
`, test.wantTarget)

			if diff := cmp.Diff(want, string(content)); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}
