# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Developerconnect resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class DeveloperconnectGa(base.Group):
  """Manage Developerconnect resources."""


