# This file contains a wrapper build configuration for testing.
load(
    "@com_google_googleapis_imports//:imports.bzl",
    "ruby_cloud_gapic_library",
)

ruby_cloud_gapic_library(
    name = "secretmanager_ruby_wrapper",
    srcs = ["//google/cloud/secretmanager/v1:secretmanager_proto_with_info"],
    extra_protoc_parameters = [
        "ruby-cloud-env-prefix=SECRET_MANAGER",
        "ruby-cloud-gem-namespace=Google::Cloud::SecretManager",
        "ruby-cloud-wrapper-of=v1",
    ],
)
