// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package php

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
)

var (
	gapicMarker    = []byte("GENERATED CODE WARNING")
	protobufMarker = []byte("Generated by the protocol buffer compiler")

	directoriesToClean = []string{
		"src",
		"tests",
		"metadata",
		"samples",
	}
)

// Clean removes all generated code from beneath the given library's
// output directory. If the output directory does not currently exist, this
// function is a no-op.
func Clean(library *config.Library) error {
	_, err := os.Stat(library.Output)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	keepSet := make(map[string]bool)
	for _, k := range library.Keep {
		keepSet[k] = true
	}

	for _, dir := range directoriesToClean {
		if err := cleanFiles(library, keepSet, dir); err != nil {
			return err
		}
	}
	return nil
}

func cleanFiles(lib *config.Library, keepSet map[string]bool, subDir string) error {
	dir := filepath.Join(lib.Output, subDir)
	_, err := os.Stat(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		relPath, err := filepath.Rel(lib.Output, path)
		if err != nil {
			return err
		}
		if keepSet[relPath] {
			return nil
		}

		// Delete gapic_metadata.json by name
		if d.Name() == "gapic_metadata.json" {
			return os.Remove(path)
		}

		// Only inspect PHP files
		if !strings.HasSuffix(d.Name(), ".php") {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		if bytes.Contains(content, gapicMarker) || bytes.Contains(content, protobufMarker) {
			return os.Remove(path)
		}

		return nil
	})
}
