package gcloud

// Command represents the top-level structure for a gcloud command definition.
type Command struct {
	ReleaseTracks []string  `yaml:"release_tracks,omitempty"`
	AutoGenerated bool      `yaml:"auto_generated,omitempty"`
	Hidden        bool      `yaml:"hidden,omitempty"`
	HelpText      HelpText  `yaml:"help_text,omitempty"`
	Arguments     Arguments `yaml:"arguments,omitempty"`
	Request       *Request  `yaml:"request,omitempty"`
	Async         *Async    `yaml:"async,omitempty"`
}

// HelpText holds the help text for the command.
type HelpText struct {
	Brief       string `yaml:"brief,omitempty"`
	Description string `yaml:"description,omitempty"`
	Examples    string `yaml:"examples,omitempty"`
}

// Arguments contains the list of parameters for the command.
type Arguments struct {
	Params []Param `yaml:"params,omitempty"`
}

// Param represents a single command-line argument or flag.
type Param struct {
	ArgName              string            `yaml:"arg_name,omitempty"`
	APIField             string            `yaml:"api_field,omitempty"`
	HelpText             string            `yaml:"help_text"`
	IsPositional         bool              `yaml:"is_positional,omitempty"`
	IsPrimaryResource    bool              `yaml:"is_primary_resource,omitempty"`
	RequestIDField       string            `yaml:"request_id_field,omitempty"`
	ResourceSpec         *ResourceSpec     `yaml:"resource_spec,omitempty"`
	Required             bool              `yaml:"required"`
	Repeated             bool              `yaml:"repeated"`
	Type                 string            `yaml:"type,omitempty"`
	Choices              []Choice          `yaml:"choices,omitempty"`
	Spec                 []ArgSpec         `yaml:"spec,omitempty"`
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

// ArgSpec defines the structure within a complex argument type, like a map's key/value.
type ArgSpec struct {
	APIField string `yaml:"api_field,omitempty"`
}

// Choice represents a single option for an enum-based argument.
type Choice struct {
	ArgValue  string `yaml:"arg_value,omitempty"`
	EnumValue string `yaml:"enum_value,omitempty"`
}

// ResourceSpec defines the structure for a gcloud resource argument.
type ResourceSpec struct {
	Name                  string      `yaml:"name,omitempty"`
	PluralName            string      `yaml:"plural_name,omitempty"`
	Collection            string      `yaml:"collection,omitempty"`
	Attributes            []Attribute `yaml:"attributes,omitempty"`
	DisableAutoCompleters bool        `yaml:"disable_auto_completers"`
}

// Attribute defines a single component of a resource's identifier.
type Attribute struct {
	ParameterName string `yaml:"parameter_name,omitempty"`
	AttributeName string `yaml:"attribute_name,omitempty"`
	Help          string `yaml:"help,omitempty"`
	Property      string `yaml:"property,omitempty"`
}

// Request defines the API request details.
type Request struct {
	APIVersion string   `yaml:"api_version,omitempty"`
	Collection []string `yaml:"collection,omitempty"`
}

// Async defines the details for handling long-running operations.
type Async struct {
	Collection []string `yaml:"collection,omitempty"`
}

