// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/sidekick/internal/api"
	"github.com/googleapis/librarian/internal/sidekick/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/internal/config/gcloudyaml"
	"gopkg.in/yaml.v3"
)

// Generate generates gcloud commands from the model.
func Generate(model *api.API, outdir string, cfg *config.Config) error {
	if cfg.Gcloud == nil {
		return fmt.Errorf("gcloud config is missing")
	}
	serviceNameParts := strings.Split(cfg.Gcloud.ServiceName, ".")
	if len(serviceNameParts) == 0 {
		return fmt.Errorf("invalid service name in gcloud.yaml: %s", cfg.Gcloud.ServiceName)
	}
	shortServiceName := serviceNameParts[0]
	surfaceDir := filepath.Join(outdir, shortServiceName, "surface")

	methodsByResource := make(map[string][]*api.Method)
	for _, service := range model.Services {
		for _, method := range service.Methods {
			collectionID := getPluralName(method, model)
			if collectionID != "" {
				methodsByResource[collectionID] = append(methodsByResource[collectionID], method)
			}
		}
	}

	for collectionID, methods := range methodsByResource {
		err := generateResourceCommands(collectionID, methods, surfaceDir, cfg, model)
		if err != nil {
			return err
		}
	}
	return nil
}

func generateResourceCommands(collectionID string, methods []*api.Method, baseDir string, cfg *config.Config, model *api.API) error {
	resourceDir := filepath.Join(baseDir, collectionID)
	partialsDir := filepath.Join(resourceDir, "_partials")
	if err := os.MkdirAll(partialsDir, 0755); err != nil {
		return fmt.Errorf("failed to create partials directory for %q: %w", collectionID, err)
	}

	for _, method := range methods {
		verb := getVerb(method.Name)
		cmd := newCommand(method, cfg, model)

		mainCmdPath := filepath.Join(resourceDir, fmt.Sprintf("%s.yaml", verb))
		if err := os.WriteFile(mainCmdPath, []byte("_PARTIALS_: true\n"), 0644); err != nil {
			return fmt.Errorf("failed to write main command file for %q: %w", method.Name, err)
		}

		track := "ga"
		partialFileName := fmt.Sprintf("_%s_%s.yaml", verb, track)
		partialCmdPath := filepath.Join(partialsDir, partialFileName)

		b, err := yaml.Marshal(cmd)
		if err != nil {
			return fmt.Errorf("failed to marshal partial command for %q: %w", method.Name, err)
		}

		if err := os.WriteFile(partialCmdPath, b, 0644); err != nil {
			return fmt.Errorf("failed to write partial command file for %q: %w", method.Name, err)
		}
	}
	return nil
}

func newCommand(method *api.Method, cfg *config.Config, model *api.API) *Command {
	rule := findHelpTextRule(method, cfg)
	apiDef := findAPI(method, cfg)
	cmd := &Command{
		AutoGenerated: true,
		Hidden:        true,
	}
	if rule != nil {
		cmd.HelpText = HelpText{
			Brief:       rule.HelpText.Brief,
			Description: rule.HelpText.Description,
			Examples:    "TODO: Add examples from " + rule.Selector,
		}
	}
	if apiDef != nil {
		for _, track := range apiDef.ReleaseTracks {
			cmd.ReleaseTracks = append(cmd.ReleaseTracks, string(track))
		}
	}
	cmd.Arguments = newArguments(method, cfg, model)
	cmd.Request = newRequest(method, cfg, model)
	if method.OperationInfo != nil {
		cmd.Async = newAsync(method, cfg)
	}
	return cmd
}

func newArguments(method *api.Method, cfg *config.Config, model *api.API) Arguments {
	args := Arguments{}
	if method.InputType == nil {
		return args
	}

	for _, field := range method.InputType.Fields {
		if field.Name == "parent" {
			continue
		}

		if isPrimaryResource(field, method) {
			param := newPrimaryResourceParam(field, method, model, cfg)
			args.Params = append(args.Params, param)
			continue
		}

		addFlattenedParams(field, field.JSONName, &args, cfg, model)
	}
	return args
}

func addFlattenedParams(field *api.Field, prefix string, args *Arguments, cfg *config.Config, model *api.API) {
	if isOutputOnly(field) || field.Name == "name" {
		return
	}

	if field.MessageType != nil && !field.Map {
		for _, f := range field.MessageType.Fields {
			addFlattenedParams(f, fmt.Sprintf("%s.%s", prefix, f.JSONName), args, cfg, model)
		}
		return
	}

	param := newParam(field, prefix, cfg, model)
	args.Params = append(args.Params, param)
}

func newParam(field *api.Field, apiField string, cfg *config.Config, model *api.API) Param {
	param := Param{
		ArgName:  ToKebabCase(field.Name),
		APIField: apiField,
		Required: field.DocumentAsRequired(),
		Repeated: field.Repeated,
	}

	if field.ResourceReference != nil {
		param.ResourceSpec = newResourceReferenceSpec(field, model, cfg)
		param.ResourceMethodParams = map[string]string{
			apiField: "{__relative_name__}",
		}
	} else if field.Map {
		param.Repeated = true
		param.Spec = []ArgSpec{
			{APIField: "key"},
			{APIField: "value"},
		}
	} else if field.EnumType != nil {
		for _, v := range field.EnumType.Values {
			if strings.HasSuffix(v.Name, "_UNSPECIFIED") {
				continue
			}
			param.Choices = append(param.Choices, Choice{
				ArgValue:  ToKebabCase(v.Name),
				EnumValue: v.Name,
			})
		}
	} else {
		param.Type = getGcloudType(field.Typez)
	}

	if rule := findFieldHelpTextRule(field, cfg); rule != nil {
		param.HelpText = rule.HelpText.Brief
	}
	return param
}

func newPrimaryResourceParam(field *api.Field, method *api.Method, model *api.API, cfg *config.Config) Param {
	resource := getResourceForMethod(method)
	pattern := ""
	if resource != nil && len(resource.Pattern) > 0 {
		pattern = resource.Pattern[0]
	}

	collectionPath := getCollectionPathFromPattern(pattern)
	shortServiceName := strings.Split(cfg.Gcloud.ServiceName, ".")[0]

	resourceName := toSnakeCase(strings.TrimSuffix(field.Name, "_id"))
	return Param{
		HelpText:          fmt.Sprintf("The %s to create.", resourceName),
		IsPositional:      true,
		IsPrimaryResource: true,
		Required:          true,
		RequestIDField:    toLowerCamelCase(field.Name),
		ResourceSpec: &ResourceSpec{
			Name:                  resourceName,
			PluralName:            getPluralName(method, model),
			Collection:            fmt.Sprintf("%s.%s", shortServiceName, collectionPath),
			DisableAutoCompleters: false,
			Attributes:            newAttributesFromPattern(pattern),
		},
	}
}

func newResourceReferenceSpec(field *api.Field, model *api.API, cfg *config.Config) *ResourceSpec {
	for _, def := range model.ResourceDefinitions {
		if def.Type == field.ResourceReference.Type {
			if len(def.Pattern) == 0 {
				return nil // Cannot proceed without a pattern
			}
			pattern := def.Pattern[0]

			pluralName := def.Plural
			if pluralName == "" {
				pluralName = getPluralFromPattern(pattern)
			}

			parts := strings.Split(pattern, "/")
			name := strings.Trim(parts[len(parts)-1], "{}")

			shortServiceName := strings.Split(cfg.Gcloud.ServiceName, ".")[0]
			baseCollectionPath := getCollectionPathFromPattern(pattern)
			fullCollectionPath := fmt.Sprintf("%s.%s", shortServiceName, baseCollectionPath)

			return &ResourceSpec{
				Name:                  name,
				PluralName:            pluralName,
				Collection:            fullCollectionPath,
				DisableAutoCompleters: true,
				Attributes:            newAttributesFromPattern(pattern),
			}
		}
	}
	return nil
}

func newAttributesFromPattern(pattern string) []Attribute {
	var attributes []Attribute
	parts := strings.Split(pattern, "/")
	for i, part := range parts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			name := strings.Trim(part, "{}")
			var parameterName string
			if i > 0 {
				parameterName = parts[i-1] + "Id"
			} else {
				// Fallback for pattern starting with variable, though unlikely for resource patterns
				parameterName = name + "sId"
			}
			attr := Attribute{
				AttributeName: name,
				ParameterName: parameterName,
				Help:          fmt.Sprintf("The %s id of the {resource} resource.", name),
			}
			if name == "project" {
				attr.Property = "core/project"
			}
			attributes = append(attributes, attr)
		}
	}
	return attributes
}

func isPrimaryResource(field *api.Field, method *api.Method) bool {
	if method.InputType == nil {
		return false
	}
	if strings.HasPrefix(method.Name, "Create") {
		resourceName := getResourceName(method)
		if resourceName != "" && field.Name == toSnakeCase(resourceName)+"_id" {
			return true
		}
	}
	if (strings.HasPrefix(method.Name, "Get") || strings.HasPrefix(method.Name, "Delete") || strings.HasPrefix(method.Name, "Update")) && field.Name == "name" {
		return true
	}
	return false
}

func getResourceName(method *api.Method) string {
	for _, f := range method.InputType.Fields {
		if msg := f.MessageType; msg != nil && msg.Resource != nil {
			return msg.Name
		}
	}
	return ""
}

func getResourceForMethod(method *api.Method) *api.Resource {
	for _, f := range method.InputType.Fields {
		if msg := f.MessageType; msg != nil && msg.Resource != nil {
			return msg.Resource
		}
	}
	return nil
}

func newRequest(method *api.Method, cfg *config.Config, model *api.API) *Request {
	return &Request{
		APIVersion: apiVersion(cfg),
		Collection: []string{fmt.Sprintf("parallelstore.projects.locations.%s", getPluralName(method, model))},
	}
}

func newAsync(method *api.Method, cfg *config.Config) *Async {
	return &Async{
		Collection: []string{"parallelstore.projects.locations.operations"},
	}
}

func apiVersion(cfg *config.Config) string {
	if cfg.Gcloud != nil && len(cfg.Gcloud.APIs) > 0 {
		return cfg.Gcloud.APIs[0].APIVersion
	}
	return ""
}

func getGcloudType(t api.Typez) string {
	switch t {
	case api.STRING_TYPE:
		return "" // Default is string
	case api.INT32_TYPE, api.INT64_TYPE, api.UINT32_TYPE, api.UINT64_TYPE:
		return "long"
	case api.BOOL_TYPE:
		return "boolean"
	case api.FLOAT_TYPE, api.DOUBLE_TYPE:
		return "float"
	default:
		return ""
	}
}

func getPluralName(method *api.Method, model *api.API) string {
	resource := getResourceForMethod(method)
	if resource != nil {
		if resource.Plural != "" {
			return resource.Plural
		}
		if len(resource.Pattern) > 0 {
			return getPluralFromPattern(resource.Pattern[0])
		}
	}
	return ""
}

func getVerb(methodName string) string {
	switch {
	case strings.HasPrefix(methodName, "Get"):
		return "describe"
	case strings.HasPrefix(methodName, "List"):
		return "list"
	case strings.HasPrefix(methodName, "Create"):
		return "create"
	case strings.HasPrefix(methodName, "Update"):
		return "update"
	case strings.HasPrefix(methodName, "Delete"):
		return "delete"
	default:
		return toSnakeCase(methodName)
	}
}

func findAPI(method *api.Method, cfg *config.Config) *gcloudyaml.API {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	if len(cfg.Gcloud.APIs) > 0 {
		return &cfg.Gcloud.APIs[0]
	}
	return nil
}

func findHelpTextRule(method *api.Method, cfg *config.Config) *gcloudyaml.HelpTextRule {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	for _, api := range cfg.Gcloud.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.MethodRules {
			if rule.Selector == method.MethodFullName() {
				return rule
			}
		}
	}
	return nil
}

func findFieldHelpTextRule(field *api.Field, cfg *config.Config) *gcloudyaml.HelpTextRule {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	for _, api := range cfg.Gcloud.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.FieldRules {
			if rule.Selector == field.ID {
				return rule
			}
		}
	}
	return nil
}

func isOutputOnly(field *api.Field) bool {
	for _, b := range field.Behavior {
		if b == api.FIELD_BEHAVIOR_OUTPUT_ONLY {
			return true
		}
	}
	return false
}

func toLowerCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.Title(parts[i])
	}
	return strings.Join(parts, "")
}

func getPluralFromPattern(pattern string) string {
	parts := strings.Split(pattern, "/")
	if len(parts) >= 2 {
		return parts[len(parts)-2]
	}
	return ""
}

func getCollectionPathFromPattern(pattern string) string {
	parts := strings.Split(pattern, "/")
	var collectionParts []string
	for i := 0; i < len(parts)-1; i++ {
		// A collection identifier is a literal segment followed by a variable segment.
		if !strings.HasPrefix(parts[i], "{") && strings.HasPrefix(parts[i+1], "{") {
			collectionParts = append(collectionParts, parts[i])
		}
	}
	return strings.Join(collectionParts, ".")
}
