// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/sidekick/internal/api"
	"github.com/googleapis/librarian/internal/sidekick/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/internal/config/gcloudyaml"
	"gopkg.in/yaml.v3"
)

// Generate generates gcloud commands from the model.
func Generate(model *api.API, outdir string, cfg *config.Config) error {
	if cfg.Gcloud == nil {
		return fmt.Errorf("gcloud config is missing")
	}
	serviceNameParts := strings.Split(cfg.Gcloud.ServiceName, ".")
	if len(serviceNameParts) == 0 {
		return fmt.Errorf("invalid service name in gcloud.yaml: %s", cfg.Gcloud.ServiceName)
	}
	shortServiceName := serviceNameParts[0]
	surfaceDir := filepath.Join(outdir, shortServiceName, "surface")

	methodsByResource := make(map[string][]*api.Method)
	for _, service := range model.Services {
		for _, method := range service.Methods {
			collectionID := getCollectionID(method, model)
			if collectionID != "" {
				methodsByResource[collectionID] = append(methodsByResource[collectionID], method)
			}
		}
	}

	for collectionID, methods := range methodsByResource {
		err := generateResourceCommands(collectionID, methods, surfaceDir, cfg)
		if err != nil {
			return err
		}
	}
	return nil
}

func generateResourceCommands(collectionID string, methods []*api.Method, baseDir string, cfg *config.Config) error {
	resourceDir := filepath.Join(baseDir, collectionID)
	partialsDir := filepath.Join(resourceDir, "_partials")
	if err := os.MkdirAll(partialsDir, 0755); err != nil {
		return fmt.Errorf("failed to create partials directory for %q: %w", collectionID, err)
	}

	for _, method := range methods {
		verb := getVerb(method.Name)
		cmd := newCommand(method, cfg)

		// Generate the main command file (e.g., create.yaml)
		mainCmdPath := filepath.Join(resourceDir, fmt.Sprintf("%s.yaml", verb))
		if err := os.WriteFile(mainCmdPath, []byte("_PARTIALS_: true\n"), 0644); err != nil {
			return fmt.Errorf("failed to write main command file for %q: %w", method.Name, err)
		}

		// Generate the partial file (e.g., _partials/_create_ga.yaml)
		// TODO: Determine the track from the config.
		track := "ga"
		partialFileName := fmt.Sprintf("_%s_%s.yaml", verb, track)
		partialCmdPath := filepath.Join(partialsDir, partialFileName)

		// The partial file is a list of commands.
		cmdList := []*Command{cmd}
		b, err := yaml.Marshal(cmdList)
		if err != nil {
			return fmt.Errorf("failed to marshal partial command for %q: %w", method.Name, err)
		}

		if err := os.WriteFile(partialCmdPath, b, 0644); err != nil {
			return fmt.Errorf("failed to write partial command file for %q: %w", method.Name, err)
		}
	}
	return nil
}

func newCommand(method *api.Method, cfg *config.Config) *Command {
	rule := findHelpTextRule(method, cfg)
	apiDef := findAPI(method, cfg)
	cmd := &Command{
		Autogenerated: true,
		Hidden:        true,
	}
	if rule != nil {
		cmd.HelpText = &CommandHelpText{
			Brief:       rule.HelpText.Brief,
			Description: rule.HelpText.Description,
		}
	}
	if apiDef != nil {
		cmd.ReleaseTracks = apiDef.ReleaseTracks
	}
	cmd.Arguments = newArguments(method, cfg)
	cmd.Request = newRequest(method, cfg)
	if method.OperationInfo != nil {
		cmd.Async = newAsync(method, cfg)
	}
	return cmd
}

func newRequest(method *api.Method, cfg *config.Config) *Request {
	if cfg.Gcloud == nil {
		return nil
	}
	serviceNameParts := strings.Split(cfg.Gcloud.ServiceName, ".")
	if len(serviceNameParts) == 0 {
		return nil
	}
	shortServiceName := serviceNameParts[0]

	var resourceType string
	if method.InputType != nil {
		for _, field := range method.InputType.Fields {
			if (field.Name == "name" || field.Name == "parent") && field.ResourceReference != nil {
				resourceType = field.ResourceReference.Type
				if resourceType == "" {
					resourceType = field.ResourceReference.ChildType
				}
				break
			}
			if msg := field.MessageType; msg != nil && msg.Resource != nil {
				if strings.ToLower(msg.Name) == field.Name {
					resourceType = msg.Resource.Type
					break
				}
			}
		}
	}

	if resourceType == "" {
		return nil
	}

	// This is a hack to get the collection from the resource definition.
	// A better approach would be to have this information in the model.
	collection := strings.ReplaceAll(resourceType, ".googleapis.com/", ".")
	collection = strings.ReplaceAll(collection, "/", ".")

	return &Request{
		APIVersion: apiVersion(cfg),
		Collection: []string{fmt.Sprintf("%s.%s", shortServiceName, collection)},
	}
}

func newAsync(method *api.Method, cfg *config.Config) *Async {
	if cfg.Gcloud == nil {
		return nil
	}
	serviceNameParts := strings.Split(cfg.Gcloud.ServiceName, ".")
	if len(serviceNameParts) == 0 {
		return nil
	}
	shortServiceName := serviceNameParts[0]
	// This is a hack to get the operations collection.
	// A better approach would be to have this information in the model.
	return &Async{
		Collection: []string{fmt.Sprintf("%s.projects.locations.operations", shortServiceName)},
	}
}

func apiVersion(cfg *config.Config) string {
	if cfg.Gcloud != nil && len(cfg.Gcloud.APIs) > 0 {
		return cfg.Gcloud.APIs[0].APIVersion
	}
	return ""
}

func newArguments(method *api.Method, cfg *config.Config) *Arguments {
	args := &Arguments{}
	if method.InputType == nil {
		return args
	}
	for _, field := range method.InputType.Fields {
		param := &Param{
			ArgName:  ToKebabCase(field.Name),
			APIField: field.Name,
			Required: field.DocumentAsRequired(),
		}
		if field.Map {
			param.Repeated = true
			param.Spec = []*Param{
				{APIField: "key"},
				{APIField: "value"},
			}
		} else if field.EnumType != nil {
			param.Type = "string"
			for _, v := range field.EnumType.Values {
				param.Choices = append(param.Choices, &Choice{
					ArgValue:  ToKebabCase(v.Name),
					EnumValue: v.Name,
				})
			}
		} else if field.MessageType != nil {
			param.Spec = newSpec(field.MessageType, field.Name, cfg)
		} else {
			param.Type = getGcloudType(field.Typez)
		}

		if isPrimaryResource(field, method) {
			param.IsPositional = true
			param.IsPrimaryResource = true
		}
		if rule := findFieldHelpTextRule(field, cfg); rule != nil {
			param.HelpText = rule.HelpText.Brief
		}
		args.Params = append(args.Params, param)
	}
	return args
}

func newSpec(message *api.Message, prefix string, cfg *config.Config) []*Param {
	var params []*Param
	for _, field := range message.Fields {
		isOutputOnly := false
		for _, b := range field.Behavior {
			if b == api.FIELD_BEHAVIOR_OUTPUT_ONLY {
				isOutputOnly = true
				break
			}
		}
		if isOutputOnly {
			continue
		}

		param := &Param{
			ArgName:  ToKebabCase(field.Name),
			APIField: fmt.Sprintf("%s.%s", prefix, field.Name),
			Required: field.DocumentAsRequired(),
		}
		if field.Map {
			param.Repeated = true
			param.Spec = []*Param{
				{APIField: "key"},
				{APIField: "value"},
			}
		} else if field.EnumType != nil {
			param.Type = "string"
			for _, v := range field.EnumType.Values {
				param.Choices = append(param.Choices, &Choice{
					ArgValue:  ToKebabCase(v.Name),
					EnumValue: v.Name,
				})
			}
		} else if field.MessageType != nil {
			param.Spec = newSpec(field.MessageType, fmt.Sprintf("%s.%s", prefix, field.Name), cfg)
		} else {
			param.Type = getGcloudType(field.Typez)
		}
		if rule := findFieldHelpTextRule(field, cfg); rule != nil {
			param.HelpText = rule.HelpText.Brief
		}
		params = append(params, param)
	}
	return params
}

func isPrimaryResource(field *api.Field, method *api.Method) bool {
	if method.InputType == nil {
		return false
	}
	// For Create methods, the primary resource ID is the field named `{resource}_id`.
	if strings.HasPrefix(method.Name, "Create") {
		for _, f := range method.InputType.Fields {
			if msg := f.MessageType; msg != nil && msg.Resource != nil {
				if field.Name == toSnakeCase(msg.Name)+"_id" {
					return true
				}
			}
		}
	}
	// For Get, Delete, and Update methods, the primary resource is the `name` field.
	if (strings.HasPrefix(method.Name, "Get") || strings.HasPrefix(method.Name, "Delete") || strings.HasPrefix(method.Name, "Update")) && field.Name == "name" {
		return true
	}
	return false
}

func getGcloudType(t api.Typez) string {
	switch t {
	case api.STRING_TYPE:
		return "string"
	case api.INT32_TYPE, api.INT64_TYPE, api.UINT32_TYPE, api.UINT64_TYPE:
		return "integer"
	case api.BOOL_TYPE:
		return "boolean"
	case api.FLOAT_TYPE, api.DOUBLE_TYPE:
		return "float"
	default:
		return ""
	}
}

func getCollectionID(method *api.Method, model *api.API) string {
	var resourceType string
	if method.InputType != nil {
		for _, field := range method.InputType.Fields {
			if (field.Name == "name" || field.Name == "parent") && field.ResourceReference != nil {
				resourceType = field.ResourceReference.Type
				if resourceType == "" {
					resourceType = field.ResourceReference.ChildType
				}
				break
			}
			if msg := field.MessageType; msg != nil && msg.Resource != nil {
				if strings.ToLower(msg.Name) == field.Name {
					resourceType = msg.Resource.Type
					break
				}
			}
		}
	}

	if resourceType == "" {
		return ""
	}

	for _, msg := range model.Messages {
		if msg.Resource != nil && msg.Resource.Type == resourceType {
			return msg.Resource.Plural
		}
	}

	return ""
}

func getVerb(methodName string) string {
	switch {
	case strings.HasPrefix(methodName, "Get"):
		return "describe"
	case strings.HasPrefix(methodName, "List"):
		return "list"
	case strings.HasPrefix(methodName, "Create"):
		return "create"
	case strings.HasPrefix(methodName, "Update"):
		return "update"
	case strings.HasPrefix(methodName, "Delete"):
		return "delete"
	default:
		return toSnakeCase(methodName)
	}
}

func findAPI(method *api.Method, cfg *config.Config) *gcloudyaml.API {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	// TODO: support more than one API.
	if len(cfg.Gcloud.APIs) > 0 {
		return &cfg.Gcloud.APIs[0]
	}
	return nil
}

func findHelpTextRule(method *api.Method, cfg *config.Config) *gcloudyaml.HelpTextRule {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	for _, api := range cfg.Gcloud.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.MethodRules {
			if rule.Selector == method.MethodFullName() {
				return rule
			}
		}
	}
	return nil
}

func findFieldHelpTextRule(field *api.Field, cfg *config.Config) *gcloudyaml.HelpTextRule {
	if cfg.Gcloud == nil || cfg.Gcloud.APIs == nil {
		return nil
	}
	for _, api := range cfg.Gcloud.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.FieldRules {
			if rule.Selector == field.ID {
				return rule
			}
		}
	}
	return nil
}
