# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Operation Methods resource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class ResourcesGa(base.Group):
  """Manage Operation Methods resource resources."""
