# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource filteredResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class FilteredResourcesGa(base.Group):
  """Manage Standard Resource filteredResource resources."""
