# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource visible_resource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class VisibleResourcesGa(base.Group):
  """Manage Standard Resource visible_resource resources."""
