# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Iam resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class IamGa(base.Group):
  """Manage Iam resources."""


