// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codec_sample

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerate(t *testing.T) {
	for _, test := range []struct {
		name         string
		model        *api.API
		wantContains []string
	}{
		{
			name: "generates readme with prologue",
			model: api.NewTestAPI(
				[]*api.Message{api.NewTestMessage("Item")},
				nil,
				[]*api.Service{api.NewTestService("ItemsService")},
			),
			wantContains: []string{
				"Code generated by sidekick. DO NOT EDIT.",
				"Copyright 2026 Google LLC",
				"Apache License, Version 2.0",
				"# Sample Codec -",
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outDir := t.TempDir()
			if err := Generate(t.Context(), test.model, outDir); err != nil {
				t.Fatal(err)
			}
			filename := filepath.Join(outDir, "README.md")
			info, err := os.Stat(filename)
			if err != nil {
				t.Fatal(err)
			}
			if info.Mode().Perm()&0o111 != 0 {
				t.Errorf("generated file should not be executable: %s (%o)", filename, info.Mode())
			}
			contents, err := os.ReadFile(filename)
			if err != nil {
				t.Fatal(err)
			}
			contentStr := string(contents)
			for _, want := range test.wantContains {
				if !strings.Contains(contentStr, want) {
					t.Errorf("output does not contain %q. Got:\n%s", want, contentStr)
				}
			}
		})
	}
}
