# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Developerconnect accountConnector resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class AccountConnectorsGa(base.Group):
  """Manage Developerconnect accountConnector resources."""


