# This file contains a wrapper build configuration for testing.
load(
    "@com_google_googleapis_imports//:imports.bzl",
    "ruby_cloud_gapic_library",
)

ruby_cloud_gapic_library(
    name = "automl_ruby_wrapper",
    srcs = ["//google/cloud/automl/v1:automl_proto_with_info"],
    extra_protoc_parameters = [
        "ruby-cloud-env-prefix=AUTOML",
        "ruby-cloud-namespace-override=AutoMl=AutoML;Automl=AutoML",
        "ruby-cloud-path-override=auto_ml=automl",
    ],
)
