// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sources"
	"github.com/googleapis/librarian/internal/testhelper"
)

func TestGenerate_ValidationErrors(t *testing.T) {
	for _, test := range []struct {
		name    string
		library *config.Library
		src     *sources.Sources
		wantErr error
	}{
		{
			name:    "nil library",
			library: nil,
			src:     nil,
			wantErr: ErrMissingCppConfig,
		},
		{
			name:    "nil cpp config",
			library: &config.Library{Name: "test-lib"},
			src:     nil,
			wantErr: ErrMissingCppConfig,
		},
		{
			name: "no apis",
			library: &config.Library{
				Name: "test-lib",
				Cpp:  &config.CppLibrary{},
			},
			src:     nil,
			wantErr: ErrNoAPIs,
		},
		{
			name: "missing googleapis source",
			library: &config.Library{
				Name: "test-lib",
				Cpp:  &config.CppLibrary{},
				APIs: []*config.API{{Path: "google/cloud/secretmanager/v1"}},
			},
			src:     nil,
			wantErr: ErrMissingGoogleapisSource,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			err := Generate(t.Context(), nil, test.library, test.src)
			if !errors.Is(err, test.wantErr) {
				t.Fatalf("expected error %v, got: %v", test.wantErr, err)
			}
		})
	}
}

func TestGenerate_MissingServiceConfig(t *testing.T) {
	lib := &config.Library{
		Name: "test-lib",
		Cpp:  &config.CppLibrary{},
		APIs: []*config.API{{Path: "nonexistent/api/v1"}},
	}
	src := &sources.Sources{Googleapis: t.TempDir()}
	err := Generate(t.Context(), nil, lib, src)
	if err == nil {
		t.Fatal("expected error for nonexistent service config, got nil")
	}
}

func TestLibraryToModelConfig_UsesOverrideServiceConfigYAMLName(t *testing.T) {
	tempDir := t.TempDir()
	overrideYAML := "custom_service.yaml"
	lib := &config.Library{
		Name: "test-lib",
		Cpp: &config.CppLibrary{
			OverrideServiceConfigYAMLName: overrideYAML,
		},
		APIs: []*config.API{{Path: "nonexistent/api/v1"}},
	}
	src := &sources.Sources{Googleapis: tempDir}
	pc := &config.Protoc{}
	modelCfg, err := libraryToModelConfig(lib, lib.APIs[0], src, pc)
	if err != nil {
		t.Fatalf("expected nil error when OverrideServiceConfigYAMLName is provided, got: %v", err)
	}
	if modelCfg.ServiceConfig != overrideYAML {
		t.Errorf("ServiceConfig mismatch: got %q, want %q", modelCfg.ServiceConfig, overrideYAML)
	}
}

func TestDefaultOutput(t *testing.T) {
	for _, test := range []struct {
		name       string
		api        string
		defaultOut string
		want       string
	}{
		{
			name:       "empty defaultOut",
			api:        "google/cloud/secretmanager/v1",
			defaultOut: "",
			want:       "google/cloud/secretmanager/v1",
		},
		{
			name:       "with defaultOut",
			api:        "google/cloud/secretmanager/v1",
			defaultOut: "generated",
			want:       "generated/google/cloud/secretmanager/v1",
		},
		{
			name:       "absolute defaultOut",
			api:        "test/v1",
			defaultOut: "/var/tmp/output",
			want:       "/var/tmp/output/test/v1",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			got := DefaultOutput(test.api, test.defaultOut)
			if diff := cmp.Diff(test.want, got); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestGenerate_Success(t *testing.T) {
	testhelper.RequireCommand(t, "protoc")

	googleapisDir, err := filepath.Abs("../../testdata/googleapis")
	if err != nil {
		t.Fatal(err)
	}
	outDir := t.TempDir()
	library := &config.Library{
		Name:                "google-cloud-secretmanager-v1",
		Output:              outDir,
		APIs:                []*config.API{{Path: "google/cloud/secretmanager/v1"}},
		SpecificationFormat: config.SpecProtobuf,
		Cpp:                 &config.CppLibrary{},
	}
	src := &sources.Sources{Googleapis: googleapisDir}
	cfg := &config.Config{}

	if err := Generate(t.Context(), cfg, library, src); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	cmakeFile := filepath.Join(outDir, "CMakeLists.txt")
	content, err := os.ReadFile(cmakeFile)
	if err != nil {
		t.Fatalf("failed to read generated CMakeLists.txt: %v", err)
	}
	if !strings.Contains(string(content), "Generated by the Codegen C++ plugin.") {
		t.Errorf("expected generated CMakeLists.txt to contain prologue banner, got:\n%s", string(content))
	}

	var headerFiles, sourceFiles []string
	err = filepath.WalkDir(outDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		relPath, err := filepath.Rel(outDir, p)
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if info.Size() == 0 {
			t.Errorf("generated file %s is empty", relPath)
		}
		if strings.HasSuffix(relPath, ".h") {
			headerFiles = append(headerFiles, relPath)
		} else if strings.HasSuffix(relPath, ".cc") {
			sourceFiles = append(sourceFiles, relPath)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(headerFiles) == 0 {
		t.Errorf("expected generated .h files, got none")
	}
	if len(sourceFiles) == 0 {
		t.Errorf("expected generated .cc files, got none")
	}
}
