# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Parallelstore instance resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
@base.Hidden
class InstancesBeta(base.Group):
  """Manage Parallelstore instance resources."""


