// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

// Command represents the top-level structure for a gcloud command definition.
// This struct is designed to be marshaled into a YAML file that the gcloud generator can
// understand and use to generate a command-line interface.
type Command struct {
	// ReleaseTracks specifies the release tracks (e.g., GA, BETA, ALPHA) for which
	// this command is available.
	// Origin: Derived from the `release_tracks` field in the `gcloud.yaml` config file.
	ReleaseTracks []string

	// Hidden specifies whether this command should be hidden from the user in
	// help text and command listings.
	// Origin: Hardcoded to `true` by this generator.
	Hidden bool

	// HelpText contains the brief and detailed help text for the command.
	// Origin: Populated from `method_rules` in the `gcloud.yaml` config file.
	HelpText HelpText

	// Arguments defines the set of flags and positional arguments for the command.
	// Origin: Generated by parsing the fields of the method's request message from the proto.
	Arguments []Arg

	// Request specifies the details of the API request to be made when the
	// command is executed.
	// Origin: Generated by `newRequest`, which determines the API version and collection.
	Request *Request

	// Async specifies the configuration for handling long-running operations.
	// Origin: Generated by `newAsync` if the proto method is annotated as a long-running operation.
	Async *Async

	// Response specifies the details of the API response.
	Response *Response

	// Update specifies configuration for update commands.
	Update *UpdateConfig

	// Output specifies configuration for command output.
	Output *OutputConfig
}

// UpdateConfig defines configuration for update commands.
type UpdateConfig struct {
	// ReadModifyUpdate indicates whether to use a read-modify-update cycle.
	ReadModifyUpdate bool

	// DisableAutoFieldMask disables the field mask auto generation.
	DisableAutoFieldMask bool
}

// OutputConfig defines configuration for command output.
type OutputConfig struct {
	// Format is the output format for the command (e.g., "table(name, ...)").
	Format string
}

// Response defines the details of the API response.
type Response struct {
	// IDField is the name of the field in the response that contains the resource ID.
	IDField string
}

// HelpText holds the brief and detailed help text for the command.
// It maps to the `help_text` section of the gcloud YAML schema.
type HelpText struct {
	// Brief is a short, one-line summary of what the command does.
	// Origin: From the `brief` field in a `method_rule` in `gcloud.yaml`.
	Brief string
	// Description is a more detailed explanation of the command's functionality.
	// Origin: From the `description` field in a `method_rule` in `gcloud.yaml`.
	Description string
	// Examples provides one or more examples of how to use the command.
	// Origin: From the `examples` field in a `method_rule` in `gcloud.yaml`.
	Examples string
}
