// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/iancoleman/strcase"
)

// CommandGroupBuilder handles the generation of gcloud CLI intermediate branching nodes.
// Unlike a CommandBuilder which generates terminal executable rules, this builder explicitly
// crafts `__init__.py` files to initialize the directory traversal context.
type CommandGroupBuilder struct {
	node *SurfaceNode
}

// NewCommandGroupBuilder instantiates a CommandGroupBuilder from a Surface tree node.
func NewCommandGroupBuilder(node *SurfaceNode) *CommandGroupBuilder {
	return &CommandGroupBuilder{node: node}
}

// Build writes out the routing scripts for the SurfaceNode.
func (b *CommandGroupBuilder) Build() error {
	if err := os.MkdirAll(b.node.Path, 0755); err != nil {
		return fmt.Errorf("failed to create directory for group %q: %w", b.node.Name, err)
	}

	data := commandGroupData{
		ServiceTitle:     b.node.ServiceTitle,
		ResourceSingular: b.node.ResourceSingular,
		ClassNamePrefix:  strcase.ToCamel(b.node.Name),
		Tracks:           b.node.Tracks,
	}

	var buf bytes.Buffer
	if err := commandGroupTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute __init__.py template for group %q: %w", b.node.Name, err)
	}

	path := filepath.Join(b.node.Path, "__init__.py")
	if err := os.WriteFile(path, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write __init__.py for group %q: %w", b.node.Name, err)
	}
	return nil
}

type commandGroupData struct {
	ServiceTitle     string
	ResourceSingular string
	ClassNamePrefix  string
	Tracks           []string
}

var commandGroupTemplate = template.Must(template.New("__init__.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(`# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage {{.ServiceTitle}}{{if .ResourceSingular}} {{.ResourceSingular}}{{end}} resources."""

from googlecloudsdk.calliope import base


{{range .Tracks}}@base.ReleaseTracks(base.ReleaseTrack.{{.}})
@base.Autogenerated
@base.Hidden
class {{$.ClassNamePrefix}}{{. | toCamel}}(base.Group):
  """Manage {{$.ServiceTitle}}{{if $.ResourceSingular}} {{$.ResourceSingular}}{{end}} resources."""


{{end}}`))
