# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: PHP
on: [push, pull_request, merge_group]
permissions:
  contents: read
jobs:
  build-and-test:
    name: ${{ matrix.job-name }}
    runs-on: ubuntu-24.04
    # Presubmit jobs must complete within 5 minutes. Integration might take longer.
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - job-name: 'Unit Tests'
            task: 'unit-test'
            timeout: 5
            sparse: true
          - job-name: 'Smoke Test'
            task: 'smoke-test'
            timeout: 5
            sparse: true
          - job-name: 'Integration Test'
            task: 'integration'
            timeout: 120
            sparse: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-librarian
        with:
          include_pnpm: 'true'
          include_python: 'true'
      - name: Checkout google-cloud-php (Sparse)
        if: matrix.sparse == true
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: googleapis/google-cloud-php
          path: google-cloud-php
          persist-credentials: false
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            librarian.yaml
            composer.json
            dev/
            # Note: If changing the target of the smoke test below, update this sparse checkout rule.
            SecretManager/
      - name: Checkout google-cloud-php (Full)
        if: matrix.sparse == false && (matrix.task != 'integration' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: googleapis/google-cloud-php
          path: google-cloud-php
          persist-credentials: false
      - name: Display Go version
        run: go version
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath
      - name: Cache Librarian Tools
        id: cache-tools
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/librarian
          key: librarian-php-tools-v2-${{ runner.os }}-${{ hashFiles('internal/config/**/*.go') }}-${{ hashFiles('google-cloud-php/librarian.yaml') }}
      - name: Run librarian install
        if: matrix.task != 'integration' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        working-directory: google-cloud-php
        run: |
          librarian install
      - name: Verify tools
        run: |
          protoc --version
          php --version
      - name: Run internal/librarian/php tests and check coverage
        if: matrix.task == 'unit-test'
        run: go run ./tool/cmd/coverage ./internal/librarian/php
      - name: Generate a single library (smoke test)
        if: matrix.task == 'smoke-test' && !(github.event_name == 'push' && github.ref == 'refs/heads/main')
        working-directory: google-cloud-php
        run: librarian generate secretmanager
      - name: Run librarian generate all (integration test)
        if: matrix.task == 'integration' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: google-cloud-php
        run: librarian generate --all
  create-issue-on-failure:
    needs: [build-and-test]
    permissions:
      contents: read
      issues: write
    if: ${{ always() && contains(needs.*.result, 'failure') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/create-issue-on-failure.yaml
    with:
      language: PHP
      repository: google-cloud-php
